<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { CircleCheck, Connection, Plus, Refresh, VideoPlay } from '@element-plus/icons-vue'
import { ElMessage } from 'element-plus'
import api from '../api'

const active = ref('sources'); const loading = ref(false); const sources = ref<any[]>([]); const tasks = ref<any[]>([]); const logs = ref<any[]>([])
const sourceDialog = ref(false); const taskDialog = ref(false); const editingSource = ref<number>(); const editingTask = ref<number>()
const sourceForm = reactive<any>({ name:'',code:'',connectorType:'DATABASE',systemType:'HIS',databaseType:'MYSQL',host:'mysql',port:3306,databaseName:'',username:'',password:'',jdbcUrl:'',enabled:true })
const taskForm = reactive<any>({ taskName:'',dataSourceId:undefined,businessType:'PATIENT',executionExpression:'30s',incrementalField:'update_time',executionContent:'SELECT * FROM table_name WHERE update_time > :lastSyncTime ORDER BY update_time',enabled:true })
const systemTypes=['HIS','LIS','EMR','PACS','PIS','OTHER']; const databaseTypes=['MYSQL','SQL_SERVER','ORACLE','POSTGRESQL','DAMENG']; const businessTypes=['PATIENT','VISIT','DIAGNOSIS','LAB','EXAM','OPERATION','MEDICATION','PATHOLOGY']

async function load() { loading.value=true; try { [sources.value,tasks.value,logs.value]=await Promise.all([api.get('/data-sources'),api.get('/collect-tasks'),api.get('/collect-logs')]) } finally { loading.value=false } }
function addSource(){ editingSource.value=undefined; Object.assign(sourceForm,{name:'',code:'',connectorType:'DATABASE',systemType:'HIS',databaseType:'MYSQL',host:'mysql',port:3306,databaseName:'',username:'',password:'',jdbcUrl:'',enabled:true}); sourceDialog.value=true }
function editSource(row:any){ editingSource.value=row.id; Object.assign(sourceForm,{name:row.name,code:row.code,connectorType:row.connector_type,systemType:row.system_type,databaseType:row.database_type,host:row.host,port:row.port,databaseName:row.database_name,username:row.username,password:'',jdbcUrl:row.jdbc_url,apiUrl:row.api_url,filePath:row.file_path,enabled:!!row.enabled}); sourceDialog.value=true }
async function saveSource(){ if(editingSource.value) await api.put(`/data-sources/${editingSource.value}`,sourceForm); else await api.post('/data-sources',sourceForm); sourceDialog.value=false; ElMessage.success('数据源已保存'); load() }
async function testSource(id:number){ const result:any=await api.post(`/data-sources/${id}/test`); ElMessage.success(`${result.message}，${result.latencyMs ?? 0} ms`) }
async function toggleSource(row:any){ await api.put(`/data-sources/${row.id}/status`,{enabled:!row.enabled}); load() }
function addTask(){ editingTask.value=undefined; Object.assign(taskForm,{taskName:'',dataSourceId:sources.value[0]?.id,businessType:'PATIENT',executionExpression:'30s',incrementalField:'update_time',executionContent:'SELECT * FROM mock_his_patient WHERE update_time > :lastSyncTime ORDER BY update_time',enabled:true}); taskDialog.value=true }
function editTask(row:any){ editingTask.value=row.id; Object.assign(taskForm,{taskName:row.task_name,dataSourceId:row.data_source_id,businessType:row.business_type,executionExpression:row.execution_expression,incrementalField:row.incremental_field,executionContent:row.execution_content,enabled:!!row.enabled}); taskDialog.value=true }
async function saveTask(){ if(editingTask.value) await api.put(`/collect-tasks/${editingTask.value}`,taskForm); else await api.post('/collect-tasks',taskForm); taskDialog.value=false; ElMessage.success('采集任务已保存'); load() }
async function execute(row:any){ const result:any=await api.post(`/collect-tasks/${row.id}/execute`); ElMessage.success(`采集完成：成功 ${result.successCount}，失败 ${result.failedCount}`); load() }
onMounted(load)
</script>

<template>
  <div v-loading="loading">
    <div class="page-toolbar"><div><h2>数据采集</h2><p>连接 HIS、LIS、EMR、PACS 等来源系统，执行增量采集并查看采集结果。</p></div><div class="toolbar-actions"><el-button :icon="Refresh" @click="load">刷新</el-button><el-button v-if="active==='sources'" type="primary" :icon="Plus" @click="addSource">新增数据源</el-button><el-button v-else-if="active==='tasks'" type="primary" :icon="Plus" @click="addTask">新增采集任务</el-button></div></div>
    <el-tabs v-model="active" class="tabs-panel">
      <el-tab-pane label="数据源" name="sources"><section class="data-panel"><el-table :data="sources">
        <el-table-column prop="name" label="名称" min-width="150"/><el-table-column prop="code" label="编码" min-width="130"/><el-table-column prop="system_type" label="系统" width="90"/><el-table-column prop="connector_type" label="连接器" width="110"/><el-table-column prop="database_type" label="数据库" width="120"/><el-table-column prop="host" label="地址" min-width="140"/><el-table-column label="状态" width="90"><template #default="{row}"><el-tag :type="row.enabled?'success':'info'">{{row.enabled?'启用':'停用'}}</el-tag></template></el-table-column><el-table-column label="操作" width="230" fixed="right"><template #default="{row}"><div class="table-actions"><el-button link type="primary" :icon="Connection" @click="testSource(row.id)">测试</el-button><el-button link @click="editSource(row)">编辑</el-button><el-button link :type="row.enabled?'danger':'success'" @click="toggleSource(row)">{{row.enabled?'停用':'启用'}}</el-button></div></template></el-table-column>
      </el-table></section></el-tab-pane>
      <el-tab-pane label="采集任务" name="tasks"><section class="data-panel"><el-table :data="tasks">
        <el-table-column prop="task_name" label="任务名称" min-width="180"/><el-table-column prop="data_source_name" label="数据源" min-width="130"/><el-table-column prop="business_type" label="业务类型" width="120"/><el-table-column prop="execution_expression" label="周期" width="90"/><el-table-column prop="last_sync_time" label="上次同步" min-width="170"/><el-table-column label="状态" width="85"><template #default="{row}"><el-tag :type="row.enabled?'success':'info'">{{row.enabled?'运行中':'已停用'}}</el-tag></template></el-table-column><el-table-column label="操作" width="170"><template #default="{row}"><el-button link type="primary" :icon="VideoPlay" @click="execute(row)">立即执行</el-button><el-button link @click="editTask(row)">编辑</el-button></template></el-table-column>
      </el-table></section></el-tab-pane>
      <el-tab-pane label="采集日志" name="logs"><el-alert title="平台按 来源系统 + 来源记录号 去重：重复采集会更新原记录，不新增重复数据。" type="info" show-icon/><section class="data-panel" style="margin-top:12px"><el-table :data="logs"><el-table-column prop="task_name" label="任务" min-width="170"/><el-table-column prop="started_at" label="开始时间" min-width="170"/><el-table-column prop="ended_at" label="结束时间" min-width="170"/><el-table-column prop="success_count" label="成功（新增或更新）" width="135"/><el-table-column prop="failed_count" label="失败" width="80"/><el-table-column label="状态" width="100"><template #default="{row}"><el-tag :type="row.status==='SUCCESS'?'success':row.status==='RUNNING'?'warning':'danger'">{{row.status==='SUCCESS'?'成功':row.status==='RUNNING'?'执行中':'失败'}}</el-tag></template></el-table-column><el-table-column prop="error_message" label="异常信息" min-width="220" show-overflow-tooltip/></el-table></section></el-tab-pane>
    </el-tabs>

    <el-dialog v-model="sourceDialog" :title="editingSource?'编辑数据源':'新增数据源'" width="min(680px, 92vw)"><el-form label-width="90px" :model="sourceForm">
      <el-row :gutter="16"><el-col :span="12"><el-form-item label="名称" required><el-input v-model="sourceForm.name"/></el-form-item></el-col><el-col :span="12"><el-form-item label="编码" required><el-input v-model="sourceForm.code"/></el-form-item></el-col></el-row>
      <el-row :gutter="16"><el-col :span="12"><el-form-item label="连接器"><el-select v-model="sourceForm.connectorType" style="width:100%"><el-option v-for="x in ['DATABASE','HTTP_API','FILE']" :key="x" :value="x"/></el-select></el-form-item></el-col><el-col :span="12"><el-form-item label="系统类型"><el-select v-model="sourceForm.systemType" style="width:100%"><el-option v-for="x in systemTypes" :key="x" :value="x"/></el-select></el-form-item></el-col></el-row>
      <template v-if="sourceForm.connectorType==='DATABASE'"><el-row :gutter="16"><el-col :span="12"><el-form-item label="数据库"><el-select v-model="sourceForm.databaseType" style="width:100%"><el-option v-for="x in databaseTypes" :key="x" :value="x"/></el-select></el-form-item></el-col><el-col :span="12"><el-form-item label="库名"><el-input v-model="sourceForm.databaseName"/></el-form-item></el-col></el-row><el-row :gutter="16"><el-col :span="16"><el-form-item label="Host"><el-input v-model="sourceForm.host"/></el-form-item></el-col><el-col :span="8"><el-form-item label="端口"><el-input-number v-model="sourceForm.port" :min="1" :max="65535" style="width:100%"/></el-form-item></el-col></el-row><el-row :gutter="16"><el-col :span="12"><el-form-item label="用户名"><el-input v-model="sourceForm.username"/></el-form-item></el-col><el-col :span="12"><el-form-item label="密码"><el-input v-model="sourceForm.password" type="password" show-password :placeholder="editingSource?'留空表示不修改':''"/></el-form-item></el-col></el-row><el-form-item label="JDBC URL"><el-input v-model="sourceForm.jdbcUrl"/></el-form-item></template>
      <el-form-item label="启用"><el-switch v-model="sourceForm.enabled"/></el-form-item>
    </el-form><template #footer><el-button @click="sourceDialog=false">取消</el-button><el-button type="primary" :icon="CircleCheck" @click="saveSource">保存</el-button></template></el-dialog>

    <el-dialog v-model="taskDialog" :title="editingTask?'编辑采集任务':'新增采集任务'" width="min(720px, 92vw)"><el-form label-width="100px" :model="taskForm"><el-form-item label="任务名称" required><el-input v-model="taskForm.taskName"/></el-form-item><el-row :gutter="16"><el-col :span="12"><el-form-item label="数据源"><el-select v-model="taskForm.dataSourceId" style="width:100%"><el-option v-for="x in sources" :key="x.id" :label="x.name" :value="x.id"/></el-select></el-form-item></el-col><el-col :span="12"><el-form-item label="业务类型"><el-select v-model="taskForm.businessType" style="width:100%"><el-option v-for="x in businessTypes" :key="x" :value="x"/></el-select></el-form-item></el-col></el-row><el-row :gutter="16"><el-col :span="12"><el-form-item label="执行周期"><el-input v-model="taskForm.executionExpression" placeholder="30s / 5m / 1h"/></el-form-item></el-col><el-col :span="12"><el-form-item label="增量字段"><el-input v-model="taskForm.incrementalField"/></el-form-item></el-col></el-row><el-form-item label="SQL / API" required><el-input v-model="taskForm.executionContent" type="textarea" :rows="5" class="mono"/></el-form-item><el-form-item label="启用"><el-switch v-model="taskForm.enabled"/></el-form-item></el-form><template #footer><el-button @click="taskDialog=false">取消</el-button><el-button type="primary" @click="saveTask">保存</el-button></template></el-dialog>
  </div>
</template>
