<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { Box, Delete, Download, Plus, Refresh, Upload } from '@element-plus/icons-vue'
import { ElMessage, ElMessageBox, type UploadFile } from 'element-plus'
import api from '../api'

const active=ref('assets');const loading=ref(false);const files=ref<any[]>([]);const tasks=ref<any[]>([]);const targets=ref<any[]>([]);const selection=ref<any[]>([])
const uploadDialog=ref(false);const versionDialog=ref(false);const selectedFile=ref<File>();const versionAsset=ref<any>()
const form=reactive<any>({fileType:'OTHER',businessType:'ATTACHMENT',businessId:undefined,displayName:''})
function formatBytes(value=0){if(!value)return '0 B';const units=['B','KB','MB','GB','TB'];const i=Math.min(Math.floor(Math.log(value)/Math.log(1024)),4);return `${(value/1024**i).toFixed(i?1:0)} ${units[i]}`}
async function load(){loading.value=true;try{[files.value,tasks.value,targets.value]=await Promise.all([api.get('/files'),api.get('/backups/tasks'),api.get('/storage-targets')])}finally{loading.value=false}}
function fileChanged(file:UploadFile){selectedFile.value=file.raw}
function openUpload(){Object.assign(form,{fileType:'OTHER',businessType:'ATTACHMENT',businessId:undefined,displayName:''});selectedFile.value=undefined;uploadDialog.value=true}
async function upload(){if(!selectedFile.value){ElMessage.warning('请选择文件');return}const data=new FormData();Object.entries(form).forEach(([key,value])=>{if(value!==undefined&&value!=='')data.append(key,String(value))});data.append('file',selectedFile.value);await api.post('/files/upload',data,{headers:{'Content-Type':'multipart/form-data'},timeout:0});uploadDialog.value=false;ElMessage.success('文件已上传');load()}
function openVersion(row:any){versionAsset.value=row;selectedFile.value=undefined;versionDialog.value=true}
async function uploadVersion(){if(!selectedFile.value)return;const data=new FormData();data.append('file',selectedFile.value);await api.post(`/files/${versionAsset.value.id}/versions`,data,{headers:{'Content-Type':'multipart/form-data'},timeout:0});versionDialog.value=false;ElMessage.success('新版本已保留');load()}
function saveBlob(blob:Blob,name:string){const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url)}
async function download(row:any){saveBlob(await api.get(`/files/${row.id}/download`,{responseType:'blob'}),row.display_name||row.file_name)}
async function batchDownload(){saveBlob(await api.post('/files/batch/download',{ids:selection.value.map(x=>x.id)},{responseType:'blob'}),'files.zip')}
async function archive(){const target=targets.value.find(x=>x.storage_class==='ARCHIVE');if(!target){ElMessage.warning('请先配置 ARCHIVE 存储');return}await api.post('/files/batch/archive',{ids:selection.value.map(x=>x.id),targetStorageId:target.id});ElMessage.success('文件已归档');load()}
async function remove(){await ElMessageBox.confirm('仅逻辑删除所选文件，不删除对象存储内容。','确认删除',{type:'warning'});await api.delete('/files/batch',{data:{ids:selection.value.map(x=>x.id)}});ElMessage.success('文件已逻辑删除');load()}
async function backup(row:any){const target=targets.value.find(x=>x.storage_class==='BACKUP');await api.post(`/backups/files/${row.id}`,target?{targetStorageId:target.id}:{});ElMessage.success('备份与 MD5 校验完成');load()}
async function showVersions(row:any){const versions:any[]=await api.get(`/files/${row.id}/versions`);ElMessageBox.alert(versions.map(x=>`V${x.version_no} · ${formatBytes(x.file_size)} · ${x.md5}`).join('\n')||'暂无版本','版本记录')}
onMounted(load)
</script>

<template>
  <div v-loading="loading"><div class="page-toolbar"><div><h2>文件中心</h2><p>统一管理数字切片、上报文件、医疗数据文件及附件版本</p></div><div class="toolbar-actions"><el-button :icon="Refresh" @click="load">刷新</el-button><el-button v-if="active==='assets'" type="primary" :icon="Plus" @click="openUpload">上传文件</el-button></div></div>
    <el-tabs v-model="active" class="tabs-panel">
      <el-tab-pane label="文件资产" name="assets"><div class="filter-row" style="margin-bottom:12px"><el-button :icon="Download" :disabled="!selection.length" @click="batchDownload">批量下载</el-button><el-button :icon="Box" :disabled="!selection.length" @click="archive">批量归档</el-button><el-button type="danger" plain :icon="Delete" :disabled="!selection.length" @click="remove">逻辑删除</el-button></div><section class="data-panel"><el-table :data="files" @selection-change="selection=$event"><el-table-column type="selection" width="48"/><el-table-column prop="file_type" label="分类" width="110"/><el-table-column prop="display_name" label="文件名称" min-width="220"/><el-table-column prop="business_type" label="业务类型" width="120"/><el-table-column label="版本" width="80"><template #default="{row}">V{{row.current_version}}</template></el-table-column><el-table-column label="大小" width="100"><template #default="{row}">{{formatBytes(row.file_size)}}</template></el-table-column><el-table-column prop="storage_target_name" label="存储位置" min-width="150"/><el-table-column prop="md5" label="MD5" min-width="220" show-overflow-tooltip/><el-table-column prop="created_at" label="创建时间" min-width="170"/><el-table-column label="操作" width="280" fixed="right"><template #default="{row}"><div class="table-actions"><el-button link :icon="Download" @click="download(row)">下载</el-button><el-button link @click="showVersions(row)">版本</el-button><el-button link :icon="Upload" @click="openVersion(row)">新版本</el-button><el-button link type="success" @click="backup(row)">备份</el-button></div></template></el-table-column></el-table></section></el-tab-pane>
      <el-tab-pane label="备份任务" name="backups"><section class="data-panel"><el-table :data="tasks"><el-table-column prop="id" label="任务" width="80"/><el-table-column prop="display_name" label="文件" min-width="220"/><el-table-column prop="target_name" label="目标" min-width="150"/><el-table-column label="进度" width="180"><template #default="{row}"><el-progress :percentage="row.progress||0" :status="row.status==='FAILED'?'exception':row.status==='SUCCESS'?'success':undefined"/></template></el-table-column><el-table-column prop="status" label="状态" width="110"/><el-table-column prop="target_md5" label="目标 MD5" min-width="220"/><el-table-column prop="error_message" label="错误" min-width="220" show-overflow-tooltip/><el-table-column prop="created_at" label="创建时间" min-width="170"/></el-table></section></el-tab-pane>
    </el-tabs>
    <el-dialog v-model="uploadDialog" title="上传文件" width="min(520px,92vw)"><el-form :model="form" label-width="86px"><el-form-item label="文件分类"><el-select v-model="form.fileType" style="width:100%"><el-option label="医疗数据文件" value="MEDICAL_DATA"/><el-option label="其他附件" value="OTHER"/></el-select></el-form-item><el-form-item label="显示名称"><el-input v-model="form.displayName"/></el-form-item><el-form-item label="文件"><el-upload drag :auto-upload="false" :limit="1" :on-change="fileChanged"><el-icon><Upload/></el-icon><div>选择文件</div></el-upload></el-form-item></el-form><template #footer><el-button @click="uploadDialog=false">取消</el-button><el-button type="primary" @click="upload">上传</el-button></template></el-dialog>
    <el-dialog v-model="versionDialog" :title="`上传新版本 · ${versionAsset?.display_name||''}`" width="min(500px,92vw)"><el-upload drag :auto-upload="false" :limit="1" :on-change="fileChanged"><el-icon><Upload/></el-icon><div>选择新版本文件</div></el-upload><template #footer><el-button @click="versionDialog=false">取消</el-button><el-button type="primary" @click="uploadVersion">保留为新版本</el-button></template></el-dialog>
  </div>
</template>
