<script setup lang="ts">
import { computed, onMounted, reactive, ref, watch } from 'vue'
import { Edit, Plus, Refresh, Search } from '@element-plus/icons-vue'
import { ElMessage } from 'element-plus'
import api from '../api'

type Field = { key:string; label:string; width?:number; type?:'date'|'datetime'|'select'|'textarea'|'number'; options?:string[] }
const definitions:Record<string,{label:string;fields:Field[]}> = {
  PATIENT:{label:'患者',fields:[{key:'patient_no',label:'患者编号'},{key:'name',label:'姓名'},{key:'gender',label:'性别',type:'select',options:['M','F','U']},{key:'birthday',label:'出生日期',type:'date'},{key:'age',label:'年龄',type:'number'},{key:'id_card',label:'身份证号'},{key:'phone',label:'电话'}]},
  VISIT:{label:'就诊',fields:[{key:'patient_id',label:'患者ID',type:'number'},{key:'visit_type',label:'就诊类型',type:'select',options:['OUTPATIENT','INPATIENT','PHYSICAL','OTHER']},{key:'visit_no',label:'就诊号'},{key:'department_code',label:'科室编码'},{key:'department_name',label:'科室名称'},{key:'doctor_code',label:'医生编码'},{key:'doctor_name',label:'医生姓名'},{key:'admission_time',label:'入院时间',type:'datetime'},{key:'discharge_time',label:'出院时间',type:'datetime'}]},
  DIAGNOSIS:{label:'诊断',fields:[{key:'patient_id',label:'患者ID',type:'number'},{key:'visit_id',label:'就诊ID',type:'number'},{key:'diagnosis_code',label:'诊断编码'},{key:'diagnosis_name',label:'诊断名称'},{key:'diagnosis_type',label:'诊断类型'},{key:'diagnosis_time',label:'诊断时间',type:'datetime'}]},
  LAB:{label:'检验',fields:[{key:'patient_id',label:'患者ID',type:'number'},{key:'visit_id',label:'就诊ID',type:'number'},{key:'item_code',label:'项目编码'},{key:'item_name',label:'项目名称'},{key:'result_value',label:'结果'},{key:'result_unit',label:'单位'},{key:'reference_range',label:'参考范围'},{key:'abnormal_flag',label:'异常标识'},{key:'result_time',label:'结果时间',type:'datetime'}]},
  EXAM:{label:'检查',fields:[{key:'patient_id',label:'患者ID',type:'number'},{key:'visit_id',label:'就诊ID',type:'number'},{key:'exam_code',label:'检查编码'},{key:'exam_name',label:'检查名称'},{key:'exam_part',label:'检查部位'},{key:'exam_result',label:'检查结果',type:'textarea'},{key:'exam_conclusion',label:'检查结论',type:'textarea'},{key:'exam_time',label:'检查时间',type:'datetime'}]},
  OPERATION:{label:'手术',fields:[{key:'patient_id',label:'患者ID',type:'number'},{key:'visit_id',label:'就诊ID',type:'number'},{key:'operation_code',label:'手术编码'},{key:'operation_name',label:'手术名称'},{key:'operation_time',label:'手术时间',type:'datetime'},{key:'operator_name',label:'术者'}]},
  MEDICATION:{label:'用药',fields:[{key:'patient_id',label:'患者ID',type:'number'},{key:'visit_id',label:'就诊ID',type:'number'},{key:'drug_code',label:'药品编码'},{key:'drug_name',label:'药品名称'},{key:'dosage',label:'剂量'},{key:'unit',label:'单位'},{key:'frequency',label:'频次'},{key:'route',label:'途径'},{key:'start_time',label:'开始时间',type:'datetime'},{key:'end_time',label:'结束时间',type:'datetime'}]},
}
const active=ref('PATIENT'); const loading=ref(false); const items=ref<any[]>([]); const total=ref(0); const page=ref(1); const size=ref(20); const keyword=ref(''); const dialog=ref(false); const editingId=ref<number>(); const form=reactive<any>({})
const fields=computed(()=>definitions[active.value].fields); const title=computed(()=>definitions[active.value].label)
async function load(){loading.value=true;try{const data:any=await api.get(`/medical-data/${active.value}`,{params:{page:page.value,size:size.value,keyword:keyword.value||undefined}});items.value=data.items;total.value=data.total}finally{loading.value=false}}
function add(){editingId.value=undefined; Object.keys(form).forEach(k=>delete form[k]); Object.assign(form,{source_system:'MANUAL',source_id:`MANUAL-${Date.now()}`}); dialog.value=true}
function edit(row:any){editingId.value=row.id;Object.keys(form).forEach(k=>delete form[k]);Object.assign(form,row);dialog.value=true}
async function save(){if(editingId.value)await api.put(`/medical-data/${active.value}/${editingId.value}`,form);else await api.post(`/medical-data/${active.value}`,form);dialog.value=false;ElMessage.success('医疗数据已保存');load()}
watch(active,()=>{page.value=1;keyword.value='';load()}); onMounted(load)
</script>

<template>
  <div v-loading="loading"><div class="page-toolbar"><div><h2>标准医疗数据</h2><p>查看采集并标准化后的核心医疗业务数据</p></div><div class="toolbar-actions"><el-input v-model="keyword" placeholder="按名称或来源检索" clearable style="width:220px" @keyup.enter="load"><template #prefix><el-icon><Search/></el-icon></template></el-input><el-button :icon="Refresh" @click="load">刷新</el-button><el-button type="primary" :icon="Plus" @click="add">新增{{title}}</el-button></div></div>
    <el-tabs v-model="active" class="tabs-panel"><el-tab-pane v-for="(def,key) in definitions" :key="key" :name="key" :label="def.label"/></el-tabs>
    <section class="data-panel"><el-table :data="items"><el-table-column prop="id" label="ID" width="70"/><el-table-column prop="source_system" label="来源" width="90"/><el-table-column prop="source_id" label="来源ID" min-width="110"/><el-table-column v-for="field in fields" :key="field.key" :prop="field.key" :label="field.label" min-width="120" show-overflow-tooltip/><el-table-column v-if="active==='PATIENT'" label="质量" width="90" fixed="right"><template #default="{row}"><el-tag :type="row.quality_status==='PASSED'?'success':row.quality_status==='FAILED'?'danger':'warning'">{{row.quality_status}}</el-tag></template></el-table-column><el-table-column label="操作" width="80" fixed="right"><template #default="{row}"><el-button link type="primary" :icon="Edit" @click="edit(row)">编辑</el-button></template></el-table-column></el-table><div class="pagination"><el-pagination v-model:current-page="page" v-model:page-size="size" layout="total, prev, pager, next" :total="total" @current-change="load"/></div></section>
    <el-dialog v-model="dialog" :title="`${editingId?'编辑':'新增'}${title}`" width="min(720px, 94vw)"><el-form :model="form" label-width="92px"><el-row :gutter="16"><el-col :span="12"><el-form-item label="来源系统" required><el-input v-model="form.source_system"/></el-form-item></el-col><el-col :span="12"><el-form-item label="来源 ID" required><el-input v-model="form.source_id"/></el-form-item></el-col></el-row><el-row :gutter="16"><el-col v-for="field in fields" :key="field.key" :span="field.type==='textarea'?24:12"><el-form-item :label="field.label"><el-select v-if="field.type==='select'" v-model="form[field.key]" clearable style="width:100%"><el-option v-for="option in field.options" :key="option" :value="option"/></el-select><el-date-picker v-else-if="field.type==='date'" v-model="form[field.key]" type="date" value-format="YYYY-MM-DD" style="width:100%"/><el-date-picker v-else-if="field.type==='datetime'" v-model="form[field.key]" type="datetime" value-format="YYYY-MM-DD HH:mm:ss" style="width:100%"/><el-input-number v-else-if="field.type==='number'" v-model="form[field.key]" style="width:100%"/><el-input v-else v-model="form[field.key]" :type="field.type==='textarea'?'textarea':'text'" :rows="3"/></el-form-item></el-col></el-row></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" @click="save">保存并校验</el-button></template></el-dialog>
  </div>
</template>
