<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { Check, Plus, Refresh } from '@element-plus/icons-vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import api from '../api'

const active=ref('errors'); const loading=ref(false); const errors=ref<any[]>([]); const rules=ref<any[]>([]); const templates=ref<any[]>([]); const fields=ref<any[]>([]); const dictionaries=ref<any[]>([]); const items=ref<any[]>([])
const correctDialog=ref(false); const selectedError=ref<any>(); const correction=reactive({value:'',note:''}); const ruleDialog=ref(false); const ruleForm=reactive<any>({businessType:'PATIENT',fieldName:'',ruleType:'NOT_NULL',ruleConfig:'',errorMessage:'',enabled:true}); const fieldDialog=ref(false); const fieldForm=reactive<any>({templateId:1,sourceField:'',targetField:'',ruleType:'DIRECT',ruleConfig:'',sortOrder:0}); const dictDialog=ref(false); const dictForm=reactive<any>({dictionaryId:1,sourceValue:'',targetValue:'',description:''})
const ruleTypes=['NOT_NULL','MIN','MAX','RANGE','REGEX','ENUM','DATE_RANGE','LENGTH']; const mappingTypes=['DIRECT','TRIM','UPPERCASE','LOWERCASE','DATE_FORMAT','NUMBER','DEFAULT_VALUE','REPLACE','DICTIONARY','CONCAT']
async function load(){loading.value=true;try{[errors.value,rules.value,templates.value,fields.value,dictionaries.value,items.value]=await Promise.all([api.get('/validation-errors'),api.get('/governance/validation-rules'),api.get('/governance/mapping-templates'),api.get('/governance/mapping-fields'),api.get('/governance/dictionaries'),api.get('/governance/dictionary-items')])}finally{loading.value=false}}
function openCorrect(row:any){selectedError.value=row;correction.value=row.current_value;correction.note='';correctDialog.value=true}
async function saveCorrection(){await api.put(`/validation-errors/${selectedError.value.id}/value`,correction);correctDialog.value=false;ElMessage.success('修正已保存，请重新校验');load()}
async function revalidate(row:any){const result:any=await api.post(`/validation-errors/${row.id}/revalidate`);ElMessage[result.passed?'success':'warning'](result.passed?'重新校验通过':'仍有未通过规则');load()}
async function ignore(row:any){await ElMessageBox.confirm('忽略后该异常不再阻止当前数据上报，是否继续？','确认忽略',{type:'warning'});await api.post(`/validation-errors/${row.id}/ignore`);load()}
function addRule(){Object.assign(ruleForm,{businessType:'PATIENT',fieldName:'',ruleType:'NOT_NULL',ruleConfig:'',errorMessage:'',enabled:true});ruleDialog.value=true}
async function saveRule(){await api.post('/governance/validation-rules',ruleForm);ruleDialog.value=false;ElMessage.success('规则已保存');load()}
function addField(){Object.assign(fieldForm,{templateId:templates.value[0]?.id,sourceField:'',targetField:'',ruleType:'DIRECT',ruleConfig:'',sortOrder:fields.value.length+1});fieldDialog.value=true}
async function saveField(){await api.post('/governance/mapping-fields',fieldForm);fieldDialog.value=false;load()}
function addDictItem(){Object.assign(dictForm,{dictionaryId:dictionaries.value[0]?.id,sourceValue:'',targetValue:'',description:''});dictDialog.value=true}
async function saveDictItem(){await api.post('/governance/dictionary-items',dictForm);dictDialog.value=false;load()}
onMounted(load)
</script>

<template>
  <div v-loading="loading"><div class="page-toolbar"><div><h2>标准化与质量闭环</h2><p>配置映射、字典和规则，处理采集产生的数据异常</p></div><div class="toolbar-actions"><el-button :icon="Refresh" @click="load">刷新</el-button><el-button v-if="active==='rules'" type="primary" :icon="Plus" @click="addRule">新增规则</el-button><el-button v-if="active==='mapping'" type="primary" :icon="Plus" @click="addField">新增映射</el-button><el-button v-if="active==='dictionary'" type="primary" :icon="Plus" @click="addDictItem">新增字典项</el-button></div></div>
    <el-tabs v-model="active" class="tabs-panel">
      <el-tab-pane label="异常数据" name="errors"><section class="data-panel"><el-table :data="errors"><el-table-column prop="patient_name" label="患者" width="110"/><el-table-column prop="business_type" label="业务类型" width="110"/><el-table-column prop="field_name" label="字段" width="110"/><el-table-column prop="current_value" label="当前值" min-width="120"/><el-table-column prop="rule_type" label="规则" width="110"/><el-table-column prop="error_message" label="异常原因" min-width="210"/><el-table-column prop="created_at" label="发生时间" min-width="170"/><el-table-column label="状态" width="105"><template #default="{row}"><el-tag :type="row.status==='PASSED'?'success':row.status==='IGNORED'?'info':row.status==='CORRECTED'?'warning':'danger'">{{row.status}}</el-tag></template></el-table-column><el-table-column label="操作" width="220" fixed="right"><template #default="{row}"><div class="table-actions"><el-button link type="primary" @click="openCorrect(row)" :disabled="!['PENDING','FAILED'].includes(row.status)">修改</el-button><el-button link type="success" :icon="Check" @click="revalidate(row)" :disabled="!['CORRECTED','FAILED','PENDING'].includes(row.status)">重新校验</el-button><el-button link @click="ignore(row)" :disabled="!['PENDING','FAILED'].includes(row.status)">忽略</el-button></div></template></el-table-column></el-table></section></el-tab-pane>
      <el-tab-pane label="校验规则" name="rules"><section class="data-panel"><el-table :data="rules"><el-table-column prop="business_type" label="业务类型" width="120"/><el-table-column prop="field_name" label="字段" width="130"/><el-table-column prop="rule_type" label="规则类型" width="120"/><el-table-column prop="rule_config" label="规则参数" min-width="160"/><el-table-column prop="error_message" label="提示信息" min-width="240"/><el-table-column label="状态" width="90"><template #default="{row}"><el-tag :type="row.enabled?'success':'info'">{{row.enabled?'启用':'停用'}}</el-tag></template></el-table-column></el-table></section></el-tab-pane>
      <el-tab-pane label="字段映射" name="mapping"><section class="data-panel"><el-table :data="fields"><el-table-column prop="template_id" label="模板ID" width="90"/><el-table-column prop="source_field" label="源字段" min-width="150"/><el-table-column prop="target_field" label="标准字段" min-width="150"/><el-table-column prop="rule_type" label="转换规则" width="140"/><el-table-column prop="rule_config" label="参数" min-width="180"/><el-table-column prop="sort_order" label="顺序" width="80"/></el-table></section></el-tab-pane>
      <el-tab-pane label="字典转换" name="dictionary"><section class="data-panel"><el-table :data="items"><el-table-column prop="dictionary_id" label="字典ID" width="100"/><el-table-column prop="source_value" label="源值" min-width="150"/><el-table-column prop="target_value" label="目标值" min-width="150"/><el-table-column prop="description" label="说明" min-width="240"/><el-table-column prop="updated_at" label="更新时间" min-width="170"/></el-table></section></el-tab-pane>
    </el-tabs>
    <el-dialog v-model="correctDialog" title="人工修正异常数据" width="min(520px,92vw)"><el-descriptions :column="1" border><el-descriptions-item label="患者">{{selectedError?.patient_name}}</el-descriptions-item><el-descriptions-item label="异常原因">{{selectedError?.error_message}}</el-descriptions-item><el-descriptions-item label="原始值">{{selectedError?.current_value}}</el-descriptions-item></el-descriptions><el-form label-width="80px" style="margin-top:20px"><el-form-item label="修正值"><el-input v-model="correction.value"/></el-form-item><el-form-item label="处理说明"><el-input v-model="correction.note" type="textarea" :rows="3"/></el-form-item></el-form><template #footer><el-button @click="correctDialog=false">取消</el-button><el-button type="primary" @click="saveCorrection">保存修正</el-button></template></el-dialog>
    <el-dialog v-model="ruleDialog" title="新增校验规则" width="min(520px,92vw)"><el-form :model="ruleForm" label-width="90px"><el-form-item label="业务类型"><el-select v-model="ruleForm.businessType" style="width:100%"><el-option v-for="x in ['PATIENT','VISIT','DIAGNOSIS','LAB','EXAM','OPERATION','MEDICATION']" :key="x" :value="x"/></el-select></el-form-item><el-form-item label="字段"><el-input v-model="ruleForm.fieldName"/></el-form-item><el-form-item label="规则类型"><el-select v-model="ruleForm.ruleType" style="width:100%"><el-option v-for="x in ruleTypes" :key="x" :value="x"/></el-select></el-form-item><el-form-item label="规则参数"><el-input v-model="ruleForm.ruleConfig" placeholder="如 0,150 或 M,F"/></el-form-item><el-form-item label="错误提示"><el-input v-model="ruleForm.errorMessage"/></el-form-item><el-form-item label="启用"><el-switch v-model="ruleForm.enabled"/></el-form-item></el-form><template #footer><el-button @click="ruleDialog=false">取消</el-button><el-button type="primary" @click="saveRule">保存</el-button></template></el-dialog>
    <el-dialog v-model="fieldDialog" title="新增字段映射" width="min(540px,92vw)"><el-form :model="fieldForm" label-width="90px"><el-form-item label="映射模板"><el-select v-model="fieldForm.templateId" style="width:100%"><el-option v-for="x in templates" :key="x.id" :label="x.name" :value="x.id"/></el-select></el-form-item><el-row :gutter="14"><el-col :span="12"><el-form-item label="源字段"><el-input v-model="fieldForm.sourceField"/></el-form-item></el-col><el-col :span="12"><el-form-item label="目标字段"><el-input v-model="fieldForm.targetField"/></el-form-item></el-col></el-row><el-form-item label="转换规则"><el-select v-model="fieldForm.ruleType" style="width:100%"><el-option v-for="x in mappingTypes" :key="x" :value="x"/></el-select></el-form-item><el-form-item label="规则参数"><el-input v-model="fieldForm.ruleConfig"/></el-form-item></el-form><template #footer><el-button @click="fieldDialog=false">取消</el-button><el-button type="primary" @click="saveField">保存</el-button></template></el-dialog>
    <el-dialog v-model="dictDialog" title="新增字典项" width="min(520px,92vw)"><el-form :model="dictForm" label-width="80px"><el-form-item label="字典"><el-select v-model="dictForm.dictionaryId" style="width:100%"><el-option v-for="x in dictionaries" :key="x.id" :label="x.name" :value="x.id"/></el-select></el-form-item><el-form-item label="源值"><el-input v-model="dictForm.sourceValue"/></el-form-item><el-form-item label="目标值"><el-input v-model="dictForm.targetValue"/></el-form-item><el-form-item label="说明"><el-input v-model="dictForm.description"/></el-form-item></el-form><template #footer><el-button @click="dictDialog=false">取消</el-button><el-button type="primary" @click="saveDictItem">保存</el-button></template></el-dialog>
  </div>
</template>
