<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { Download, Plus, Refresh, Promotion, VideoPlay } from '@element-plus/icons-vue'
import { ElMessage } from 'element-plus'
import api from '../api'
import { useAuthStore } from '../stores/auth'

const auth=useAuthStore();const active=ref('cases');const loading=ref(false);const batches=ref<any[]>([]);const cases=ref<any[]>([]);const templates=ref<any[]>([]);const plans=ref<any[]>([]);const specs=ref<any[]>([]);const jobs=ref<any[]>([]);const prechecks=ref<any[]>([]);const transfers=ref<any[]>([]);const selectedCases=ref<any[]>([]);const records=ref<any[]>([]);const selected=ref<any>();const failMode=ref(false)
const generateDialog=ref(false);const detailDialog=ref(false);const templateDialog=ref(false);const planDialog=ref(false)
const form=reactive<any>({reportType:'PATHOLOGY_PACKAGE',format:'ZIP',senderType:'HTTP',endpoint:'',templateId:undefined});const templateForm=reactive<any>({name:'病理切片一键上报',reportType:'PATHOLOGY',format:'ZIP',senderType:'HTTP',endpoint:'',includeSlide:true,businessType:'PATHOLOGY',scheduleEnabled:true,enabled:true});const planForm=reactive<any>({name:'每日病理上报',templateId:undefined,frequencyType:'DAILY',cronExpression:'0 0 2 * * *',enabled:true})
async function load(){loading.value=true;try{batches.value=await api.get('/report-batches');cases.value=await api.get('/report-batches/pending-cases');if(auth.hasAny(['REPORT_GENERATE'])){[templates.value,plans.value,specs.value,jobs.value,prechecks.value,transfers.value,failMode.value]=await Promise.all([api.get('/configuration/report-templates'),api.get('/report-plans'),api.get('/report-specs'),api.get('/report-jobs'),api.get('/report-prechecks'),api.get('/mock-resumable/sessions'),api.get('/mock-report/mode').then((x:any)=>!!x.fail)])}}finally{loading.value=false}}
function openGenerate(){form.templateId=templates.value.find(x=>x.business_type==='PATHOLOGY'||x.report_type?.startsWith('PATHOLOGY'))?.id;generateDialog.value=true}
async function create(){const payload={...form,caseIds:selectedCases.value.map(x=>x.id)};const result:any=await api.post('/report-batches',payload);generateDialog.value=false;ElMessage.success(`批次 ${result.batch.batch_no} 已生成`);load()}
async function send(row:any){const result:any=await api.post(`/report-batches/${row.id}/send`);if(result.success)ElMessage.success('上报成功');else ElMessage.error(`上报失败：${result.message}`);load()}
async function toggleFail(){await api.put('/mock-report/mode',{fail:failMode.value});ElMessage.info(failMode.value?'Mock 接收端已切换为 HTTP 500':'Mock 接收端已恢复成功响应')}
async function details(row:any){selected.value=row;records.value=await api.get(`/report-batches/${row.id}/records`);detailDialog.value=true}
async function download(row:any){const blob:Blob=await api.get(`/report-batches/${row.id}/download`,{responseType:'blob'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=row.file_path?.split(/[\\/]/).pop()||`${row.batch_no}.${row.format.toLowerCase()}`;a.click();URL.revokeObjectURL(url)}
async function saveTemplate(){await api.post('/configuration/report-templates',templateForm);templateDialog.value=false;ElMessage.success('模板已保存');load()}
function openPlan(){planForm.templateId=templates.value[0]?.id;planDialog.value=true}
async function savePlan(){await api.post('/report-plans',planForm);planDialog.value=false;ElMessage.success('上报计划已保存');load()}
async function runPlan(row:any){const result:any=await api.post(`/report-plans/${row.id}/run`);ElMessage.success(`已生成并发送批次 ${result.batchId}`);load()}
function statusType(status:string){return status==='SUCCESS'?'success':status==='FAILED'?'danger':['GENERATING','REPORTING'].includes(status)?'warning':'info'}
onMounted(load)
</script>

<template>
  <div v-loading="loading"><div class="page-toolbar"><div><h2>病理数据与数字切片上报</h2><p>质量校验、病例选择、病理 ZIP、批次发送与定时计划</p></div><div class="toolbar-actions"><el-button :icon="Refresh" @click="load">刷新</el-button><el-button v-if="auth.hasAny(['REPORT_GENERATE'])" type="primary" :icon="Plus" :disabled="active==='cases'&&!selectedCases.length" @click="active==='plans'?openPlan():active==='templates'?templateDialog=true:openGenerate()">{{active==='plans'?'新增计划':active==='templates'?'新增模板':'一键上报'}}</el-button></div></div>
    <el-tabs v-model="active" class="tabs-panel">
      <el-tab-pane label="待上报病例" name="cases"><section class="data-panel"><el-table :data="cases" @selection-change="selectedCases=$event"><el-table-column type="selection" width="48"/><el-table-column prop="pathology_no" label="病理号" min-width="150"/><el-table-column prop="patient_name" label="患者" width="110"/><el-table-column prop="specimen_type_code" label="标本类型" width="120"/><el-table-column prop="pathology_diagnosis" label="病理诊断" min-width="220"/><el-table-column prop="slide_count" label="切片数量" width="100"/><el-table-column label="质量状态" width="110"><template #default="{row}"><el-tag :type="row.quality_status==='PASSED'?'success':'warning'">{{row.quality_status||'PENDING'}}</el-tag></template></el-table-column><el-table-column label="上报状态" width="110"><template #default="{row}"><el-tag effect="plain">{{row.report_status}}</el-tag></template></el-table-column></el-table></section></el-tab-pane>
      <el-tab-pane label="上报批次" name="batches"><div class="filter-row" style="margin-bottom:12px"><span>模拟 HTTP 500</span><el-switch v-model="failMode" :disabled="!auth.hasAny(['REPORT_SEND'])" @change="toggleFail"/></div><section class="data-panel"><el-table :data="batches"><el-table-column prop="batch_no" label="批次号" min-width="190"/><el-table-column prop="report_type" label="业务类型" min-width="145"/><el-table-column prop="format" label="格式" width="80"/><el-table-column prop="total_count" label="病例数" width="85"/><el-table-column label="状态" width="110"><template #default="{row}"><el-tag :type="statusType(row.status)">{{row.status}}</el-tag></template></el-table-column><el-table-column prop="retry_count" label="重试" width="75"/><el-table-column prop="next_retry_time" label="下次重试" min-width="170"/><el-table-column prop="last_error" label="错误" min-width="220" show-overflow-tooltip/><el-table-column prop="created_at" label="创建时间" min-width="170"/><el-table-column label="操作" width="230" fixed="right"><template #default="{row}"><el-button link @click="details(row)">明细</el-button><el-button v-if="auth.hasAny(['REPORT_SEND'])" link type="success" :icon="Promotion" :disabled="!['READY','FAILED'].includes(row.status)" @click="send(row)">发送</el-button><el-button link :icon="Download" :disabled="!row.file_path" @click="download(row)">下载</el-button></template></el-table-column></el-table></section></el-tab-pane>
      <el-tab-pane v-if="auth.hasAny(['REPORT_GENERATE'])" label="上报模板" name="templates"><section class="data-panel"><el-table :data="templates"><el-table-column prop="name" label="模板名称" min-width="220"/><el-table-column prop="report_type" label="业务类型" width="160"/><el-table-column prop="format" label="格式" width="90"/><el-table-column prop="sender_type" label="发送方式" width="110"/><el-table-column label="包含切片" width="100"><template #default="{row}">{{row.include_slide?'是':'否'}}</template></el-table-column><el-table-column prop="endpoint" label="接收地址" min-width="250" show-overflow-tooltip/><el-table-column label="状态" width="90"><template #default="{row}"><el-tag :type="row.enabled?'success':'info'">{{row.enabled?'启用':'停用'}}</el-tag></template></el-table-column></el-table></section></el-tab-pane>
      <el-tab-pane v-if="auth.hasAny(['REPORT_GENERATE'])" label="上报计划" name="plans"><section class="data-panel"><el-table :data="plans"><el-table-column prop="name" label="计划名称" min-width="200"/><el-table-column prop="template_name" label="模板" min-width="200"/><el-table-column prop="frequency_type" label="频率" width="100"/><el-table-column prop="priority" label="优先级" width="80"/><el-table-column prop="cron_expression" label="Cron" min-width="150"/><el-table-column prop="last_run_time" label="上次执行" min-width="170"/><el-table-column prop="next_run_time" label="下次执行" min-width="170"/><el-table-column label="状态" width="90"><template #default="{row}"><el-tag :type="row.enabled?'success':'info'">{{row.enabled?'启用':'停用'}}</el-tag></template></el-table-column><el-table-column label="操作" width="110"><template #default="{row}"><el-button link :icon="VideoPlay" @click="runPlan(row)">立即执行</el-button></template></el-table-column></el-table></section></el-tab-pane>
      <el-tab-pane v-if="auth.hasAny(['REPORT_GENERATE'])" label="上报规范" name="specs"><section class="data-panel"><el-alert title="当前内置规范为 DEMO_LOCAL_PATHOLOGY_V1，非正式卫健委规范；正式字段和签名待外部提供。" type="warning" show-icon/><el-table :data="specs" style="margin-top:12px"><el-table-column prop="spec_code" label="规范编码"/><el-table-column prop="spec_name" label="名称"/><el-table-column prop="version" label="版本"/><el-table-column prop="file_format" label="格式"/><el-table-column prop="enabled" label="状态"><template #default="{row}"><el-tag :type="row.enabled?'success':'info'">{{row.enabled?'启用':'停用'}}</el-tag></template></el-table-column></el-table></section></el-tab-pane>
      <el-tab-pane v-if="auth.hasAny(['REPORT_GENERATE'])" label="上报任务" name="jobs"><section class="data-panel"><el-table :data="jobs"><el-table-column prop="job_no" label="任务编号"/><el-table-column prop="trigger_type" label="触发"/><el-table-column prop="scheduled_at" label="计划时间"/><el-table-column prop="priority" label="优先级"/><el-table-column prop="status" label="状态"/><el-table-column prop="error_message" label="失败原因" show-overflow-tooltip/></el-table></section></el-tab-pane>
      <el-tab-pane v-if="auth.hasAny(['REPORT_GENERATE'])" label="预审核" name="prechecks"><section class="data-panel"><el-table :data="prechecks"><el-table-column prop="id" label="审核ID"/><el-table-column prop="job_id" label="任务"/><el-table-column prop="status" label="状态"/><el-table-column prop="failed_count" label="错误"/><el-table-column prop="warning_count" label="警告"/><el-table-column prop="finished_at" label="完成时间"/></el-table></section></el-tab-pane>
      <el-tab-pane v-if="auth.hasAny(['REPORT_SEND'])" label="传输监控" name="transfers"><section class="data-panel"><el-table :data="transfers"><el-table-column prop="id" label="Session"/><el-table-column prop="total_bytes" label="总大小"/><el-table-column prop="uploaded_bytes" label="已上传"/><el-table-column prop="completed_chunks" label="完成Chunk"/><el-table-column prop="total_chunks" label="总Chunk"/><el-table-column prop="status" label="状态"/><el-table-column prop="last_activity_at" label="最后活动"/></el-table></section></el-tab-pane>
    </el-tabs>
    <el-dialog v-model="generateDialog" title="生成上报批次" width="min(540px,92vw)"><el-form :model="form" label-width="90px"><el-form-item label="上报模板"><el-select v-model="form.templateId" clearable style="width:100%"><el-option v-for="x in templates" :key="x.id" :label="x.name" :value="x.id"/></el-select></el-form-item><el-form-item label="业务类型"><el-select v-model="form.reportType" style="width:100%"><el-option label="病理数据 + 数字切片" value="PATHOLOGY_PACKAGE"/><el-option label="病理数据" value="PATHOLOGY"/><el-option label="患者数据" value="PATIENT"/></el-select></el-form-item><el-form-item label="文件格式"><el-segmented v-model="form.format" :options="form.reportType==='PATHOLOGY_PACKAGE'?['ZIP']:['JSON','XML','CSV','ZIP']"/></el-form-item><el-form-item label="发送方式"><el-segmented v-model="form.senderType" :options="['HTTP','FILE']"/></el-form-item><el-form-item label="接收地址"><el-input v-model="form.endpoint" placeholder="留空使用默认接收端"/></el-form-item></el-form><template #footer><el-button @click="generateDialog=false">取消</el-button><el-button type="primary" @click="create">生成文件</el-button></template></el-dialog>
    <el-dialog v-model="templateDialog" title="新增上报模板" width="min(540px,92vw)"><el-form :model="templateForm" label-width="90px"><el-form-item label="模板名称"><el-input v-model="templateForm.name"/></el-form-item><el-form-item label="业务类型"><el-select v-model="templateForm.reportType"><el-option label="病理数据" value="PATHOLOGY"/><el-option label="患者数据" value="PATIENT"/></el-select></el-form-item><el-form-item label="包含切片"><el-switch v-model="templateForm.includeSlide"/></el-form-item><el-form-item label="发送方式"><el-segmented v-model="templateForm.senderType" :options="['HTTP','FILE']"/></el-form-item><el-form-item label="接收地址"><el-input v-model="templateForm.endpoint"/></el-form-item></el-form><template #footer><el-button @click="templateDialog=false">取消</el-button><el-button type="primary" @click="saveTemplate">保存</el-button></template></el-dialog>
    <el-dialog v-model="planDialog" title="新增上报计划" width="min(520px,92vw)"><el-form :model="planForm" label-width="90px"><el-form-item label="计划名称"><el-input v-model="planForm.name"/></el-form-item><el-form-item label="模板"><el-select v-model="planForm.templateId" style="width:100%"><el-option v-for="x in templates" :key="x.id" :label="x.name" :value="x.id"/></el-select></el-form-item><el-form-item label="频率"><el-segmented v-model="planForm.frequencyType" :options="['MANUAL','HOURLY','DAILY','CRON']"/></el-form-item><el-form-item v-if="planForm.frequencyType==='CRON'" label="Cron"><el-input v-model="planForm.cronExpression"/></el-form-item><el-form-item label="启用"><el-switch v-model="planForm.enabled"/></el-form-item></el-form><template #footer><el-button @click="planDialog=false">取消</el-button><el-button type="primary" @click="savePlan">保存</el-button></template></el-dialog>
    <el-dialog v-model="detailDialog" :title="`批次明细 · ${selected?.batch_no||''}`" width="min(780px,94vw)"><el-table :data="records"><el-table-column prop="business_type" label="业务类型"/><el-table-column prop="business_id" label="业务ID"/><el-table-column label="状态"><template #default="{row}"><el-tag :type="statusType(row.status)">{{row.status}}</el-tag></template></el-table-column><el-table-column prop="error_message" label="错误信息" min-width="240"/></el-table></el-dialog>
  </div>
</template>
