<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { Download, Plus, Refresh, Promotion } from '@element-plus/icons-vue'
import { ElMessage } from 'element-plus'
import api from '../api'

const loading=ref(false); const batches=ref<any[]>([]); const generateDialog=ref(false); const detailDialog=ref(false); const records=ref<any[]>([]); const selected=ref<any>(); const failMode=ref(false); const form=reactive<any>({reportType:'PATIENT',format:'JSON',senderType:'HTTP',endpoint:''})
async function load(){loading.value=true;try{[batches.value,failMode.value]=await Promise.all([api.get('/report-batches'),api.get('/mock-report/mode').then((x:any)=>!!x.fail)])}finally{loading.value=false}}
async function create(){const result:any=await api.post('/report-batches',form);generateDialog.value=false;ElMessage.success(`批次 ${result.batch.batch_no} 已生成`);load()}
async function send(row:any){const result:any=await api.post(`/report-batches/${row.id}/send`);if(result.success)ElMessage.success('上报成功');else ElMessage.error(`上报失败：${result.message}`);load()}
async function toggleFail(){await api.put('/mock-report/mode',{fail:failMode.value});ElMessage.info(failMode.value?'Mock 接收端已切换为 HTTP 500':'Mock 接收端已恢复成功响应')}
async function details(row:any){selected.value=row;records.value=await api.get(`/report-batches/${row.id}/records`);detailDialog.value=true}
async function download(row:any){const response=await fetch(`/api/report-batches/${row.id}/download`,{headers:{Authorization:`Bearer ${localStorage.getItem('medical_token')}`}});if(!response.ok){ElMessage.error('下载失败');return}const blob=await response.blob();const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=row.file_path?.split(/[\\/]/).pop()||`${row.batch_no}.${row.format.toLowerCase()}`;a.click();URL.revokeObjectURL(url)}
function statusType(status:string){return status==='SUCCESS'?'success':status==='FAILED'?'danger':['GENERATING','REPORTING'].includes(status)?'warning':'info'}
onMounted(load)
</script>

<template>
  <div v-loading="loading"><div class="page-toolbar"><div><h2>上报批次</h2><p>生成标准数据包，发送并跟踪每条业务记录</p></div><div class="toolbar-actions"><span style="display:flex;align-items:center;gap:8px;font-size:13px;color:var(--muted)">模拟失败 <el-switch v-model="failMode" @change="toggleFail"/></span><el-button :icon="Refresh" @click="load">刷新</el-button><el-button type="primary" :icon="Plus" @click="generateDialog=true">生成上报</el-button></div></div>
    <section class="data-panel"><el-table :data="batches"><el-table-column prop="batch_no" label="批次号" min-width="190"/><el-table-column prop="report_type" label="上报类型" width="110"/><el-table-column prop="format" label="格式" width="80"/><el-table-column prop="sender_type" label="发送方式" width="100"/><el-table-column prop="total_count" label="总数" width="75"/><el-table-column prop="success_count" label="成功" width="75"/><el-table-column prop="failed_count" label="失败" width="75"/><el-table-column label="状态" width="110"><template #default="{row}"><el-tag :type="statusType(row.status)">{{row.status}}</el-tag></template></el-table-column><el-table-column prop="retry_count" label="重试" width="75"/><el-table-column prop="next_retry_time" label="下次重试" min-width="170"/><el-table-column prop="created_at" label="创建时间" min-width="170"/><el-table-column label="操作" width="230" fixed="right"><template #default="{row}"><div class="table-actions"><el-button link type="primary" @click="details(row)">明细</el-button><el-button link type="success" :icon="Promotion" :disabled="!['READY','FAILED'].includes(row.status)" @click="send(row)">{{row.status==='FAILED'?'重新上报':'立即上报'}}</el-button><el-button link :icon="Download" :disabled="!row.file_path" @click="download(row)">下载</el-button></div></template></el-table-column></el-table></section>
    <el-dialog v-model="generateDialog" title="生成上报批次" width="min(520px,92vw)"><el-form :model="form" label-width="90px"><el-form-item label="业务类型"><el-select v-model="form.reportType" style="width:100%"><el-option label="患者标准数据" value="PATIENT"/></el-select></el-form-item><el-form-item label="文件格式"><el-segmented v-model="form.format" :options="['JSON','XML','CSV','ZIP']"/></el-form-item><el-form-item label="发送方式"><el-segmented v-model="form.senderType" :options="['HTTP','FILE']"/></el-form-item><el-form-item :label="form.senderType==='HTTP'?'接收地址':'输出目录'"><el-input v-model="form.endpoint" :placeholder="form.senderType==='HTTP'?'留空使用 Mock 接收端':'留空使用默认 outbox'"/></el-form-item></el-form><template #footer><el-button @click="generateDialog=false">取消</el-button><el-button type="primary" @click="create">生成文件</el-button></template></el-dialog>
    <el-dialog v-model="detailDialog" :title="`批次明细 · ${selected?.batch_no||''}`" width="min(780px,94vw)"><el-table :data="records"><el-table-column prop="business_type" label="业务类型"/><el-table-column prop="business_id" label="业务ID"/><el-table-column label="状态"><template #default="{row}"><el-tag :type="statusType(row.status)">{{row.status}}</el-tag></template></el-table-column><el-table-column prop="error_message" label="错误信息" min-width="240" show-overflow-tooltip/></el-table></el-dialog>
  </div>
</template>
