<script setup lang="ts">
import { onMounted, reactive, ref, watch } from 'vue'
import { Download, Edit, Plus, Promotion, Refresh, VideoPlay } from '@element-plus/icons-vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { useRoute } from 'vue-router'
import api from '../api'
import { useAuthStore } from '../stores/auth'
import { frequencyLabel, priorityLabel, statusLabel, statusType } from '../utils/status'

const auth = useAuthStore()
const route = useRoute()
const active = ref(String(route.query.tab || 'plans'))
const loading = ref(false)
const cases = ref<any[]>([])
const batches = ref<any[]>([])
const templates = ref<any[]>([])
const plans = ref<any[]>([])
const specs = ref<any[]>([])
const jobs = ref<any[]>([])
const prechecks = ref<any[]>([])
const transfers = ref<any[]>([])
const selectedCases = ref<any[]>([])
const records = ref<any[]>([])
const issues = ref<any[]>([])
const selected = ref<any>()
const selectedPrecheck = ref<any>()
const selectedIssue = ref<any>()
const failMode = ref(false)
const detailDialog = ref(false)
const issueDialog = ref(false)
const issueEditDialog = ref(false)
const jobDialog = ref(false)
const templateDialog = ref(false)
const specDialog = ref(false)
const planDialog = ref(false)
const editingTemplateId = ref<number>()
const selectedPlan = ref<any>()
const issueForm = reactive({ newValue: '', reason: '' })
const templateForm = reactive<any>({ name: '病理数据上报文件模板', reportType: 'PATHOLOGY', format: 'ZIP', senderType: 'HTTP', endpoint: '', includeSlide: true, businessType: 'PATHOLOGY', scheduleEnabled: true, enabled: true })
const specForm = reactive<any>({ specCode: '', specName: '', authorityName: '', regionCode: '', businessType: 'PATIENT', version: '1.0', fileFormat: 'JSON', transportMode: 'HTTP', defaultFrequency: 'DAILY', demo: true, enabled: true })
const planForm = reactive<any>({ name: '每日医疗数据上报', templateId: undefined, specId: undefined, frequencyType: 'DAILY', executionTime: '02:00:00', cronExpression: '', priority: 5, enabled: true })
const jobForm = reactive<any>({ specId: undefined, scheduledAt: '', priority: 5 })

const priorityOptions = [{ value: 9, label: '高' }, { value: 5, label: '中' }, { value: 1, label: '低' }]
const frequencyOptions = [{ value: 'MANUAL', label: '手动' }, { value: 'HOURLY', label: '每小时' }, { value: 'DAILY', label: '每日' }, { value: 'WEEKLY', label: '每周' }, { value: 'MONTHLY', label: '每月' }, { value: 'CRON', label: '自定义周期' }]

async function load() {
  loading.value = true
  try {
    const requests: Promise<any>[] = [api.get('/report-batches'), api.get('/report-batches/pending-cases')]
    if (auth.hasAny(['REPORT_GENERATE'])) requests.push(api.get('/configuration/report-templates'), api.get('/report-plans'), api.get('/report-specs'), api.get('/report-jobs'), api.get('/report-prechecks'))
    if (auth.hasAny(['REPORT_SEND'])) requests.push(api.get('/mock-resumable/sessions'), api.get('/mock-report/mode'))
    const values = await Promise.all(requests)
    batches.value = values[0]
    cases.value = values[1]
    let i = 2
    if (auth.hasAny(['REPORT_GENERATE'])) {
      templates.value = values[i++]; plans.value = values[i++]; specs.value = values[i++]; jobs.value = values[i++]; prechecks.value = values[i++]
    }
    if (auth.hasAny(['REPORT_SEND'])) { transfers.value = values[i++]; failMode.value = !!values[i].fail }
  } finally { loading.value = false }
}
function openJob() { jobForm.specId = specs.value.find((x) => x.enabled)?.id; jobForm.scheduledAt = ''; jobForm.priority = 5; jobDialog.value = true }
async function createJob() {
  if (!jobForm.specId) { ElMessage.warning('请先选择上报平台规范'); return }
  const job: any = await api.post('/report-jobs', { specId: jobForm.specId, caseIds: selectedCases.value.map((x) => x.id), priority: Number(jobForm.priority), scheduledAt: jobForm.scheduledAt || undefined })
  const precheck: any = await api.post('/report-jobs/' + job.id + '/precheck')
  jobDialog.value = false
  ElMessage.info('上报任务已创建，预审核编号 ' + precheck.id)
  await load(); active.value = 'prechecks'
}
async function runPrecheck(row: any) { const result: any = await api.post('/report-jobs/' + (row.job_id || row.id) + '/precheck'); ElMessage.info('预审核已启动（' + result.id + '）'); await load() }
async function generateJob(row: any) { const result: any = await api.post('/report-jobs/' + row.id + '/generate'); ElMessage.success('上报文件已生成，记录号 ' + result.batchId); await load() }
async function sendJob(row: any) { const result: any = await api.post('/report-jobs/' + row.id + '/send'); ElMessage[result.success ? 'success' : 'error'](result.success ? '上报成功' : '上报失败：' + result.message); await load() }
async function showIssues(row: any) { selectedPrecheck.value = row; selectedIssue.value = undefined; issues.value = await api.get('/report-prechecks/' + row.id + '/issues'); issueDialog.value = true }
function openIssueEdit(row: any) { selectedIssue.value = row; issueForm.newValue = row.current_value ?? ''; issueForm.reason = ''; issueDialog.value = false; issueEditDialog.value = true }
async function saveIssue() {
  if (!selectedIssue.value || !selectedPrecheck.value) return
  await api.post('/report-prechecks/' + selectedPrecheck.value.id + '/issues/' + selectedIssue.value.id + '/ignore', { newValue: issueForm.newValue, reason: issueForm.reason || '人工修改后重新审核' })
  issueEditDialog.value = false
  ElMessage.success('修改已登记，请重新审核')
  await rerunPrecheck(selectedPrecheck.value)
}
async function rerunPrecheck(row: any) { if (!row) return; await api.post('/report-prechecks/' + row.id + '/rerun'); ElMessage.info('已重新审核'); await load() }
async function ignoreIssue(row: any) { if (!selectedPrecheck.value) return; await ElMessageBox.confirm('忽略后该问题不再阻断本次任务，是否继续？', '确认忽略', { type: 'warning' }); await api.post('/report-prechecks/' + selectedPrecheck.value.id + '/issues/' + row.id + '/ignore', { reason: '授权忽略' }); await showIssues(selectedPrecheck.value) }
async function details(row: any) { selected.value = row; records.value = await api.get('/report-batches/' + row.id + '/records'); detailDialog.value = true }
async function download(row: any) { const blob: Blob = await api.get('/report-batches/' + row.id + '/download', { responseType: 'blob' }); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; const name = String(row.file_path || '').replaceAll('\\\\', '/').split('/').pop(); a.download = name || String(row.batch_no) + '.' + String(row.format || 'zip').toLowerCase(); a.click(); URL.revokeObjectURL(url) }
async function toggleFail() { await api.put('/mock-report/mode', { fail: failMode.value }); ElMessage.info(failMode.value ? '模拟接收端已切换为失败响应' : '模拟接收端已恢复成功响应') }
function openTemplate(row?: any) { editingTemplateId.value = row?.id; Object.assign(templateForm, row ? { name: row.name, reportType: row.report_type, format: row.format, senderType: row.sender_type, endpoint: row.endpoint || '', includeSlide: !!row.include_slide, businessType: row.business_type || row.report_type, scheduleEnabled: !!row.schedule_enabled, enabled: !!row.enabled } : { name: '病理数据上报文件模板', reportType: 'PATHOLOGY', format: 'ZIP', senderType: 'HTTP', endpoint: '', includeSlide: true, businessType: 'PATHOLOGY', scheduleEnabled: true, enabled: true }); templateDialog.value = true }
async function saveTemplate() { const url = '/configuration/report-templates' + (editingTemplateId.value ? '/' + editingTemplateId.value : ''); if (editingTemplateId.value) await api.put(url, templateForm); else await api.post(url, templateForm); templateDialog.value = false; ElMessage.success('报告模板已保存'); await load() }
function openSpec() { Object.assign(specForm, { specCode: 'DEMO_CUSTOM_' + Date.now(), specName: '示例上报平台规范', authorityName: '示例主管部门', regionCode: 'DEMO', businessType: 'PATIENT', version: '1.0', fileFormat: 'JSON', transportMode: 'HTTP', defaultFrequency: 'DAILY', demo: true, enabled: true }); specDialog.value = true }
async function saveSpec() { await api.post('/report-specs', specForm); specDialog.value = false; ElMessage.success('多平台上报规范已保存'); await load() }
function openPlan(row?: any) { selectedPlan.value = row; Object.assign(planForm, row ? { name: row.name, templateId: row.template_id, specId: row.spec_id, frequencyType: row.frequency_type, executionTime: row.execution_time || '02:00:00', cronExpression: row.cron_expression || '', priority: Number(row.priority || 5), enabled: !!row.enabled } : { name: '每日医疗数据上报', templateId: templates.value[0]?.id, specId: specs.value.find((x) => x.enabled)?.id, frequencyType: 'DAILY', executionTime: '02:00:00', cronExpression: '', priority: 5, enabled: true }); planDialog.value = true }
async function savePlan() { const url = '/report-plans' + (selectedPlan.value ? '/' + selectedPlan.value.id : ''); if (selectedPlan.value) await api.put(url, planForm); else await api.post(url, planForm); planDialog.value = false; ElMessage.success('上报任务调度已保存'); await load() }
async function removePlan(row: any) { await ElMessageBox.confirm('删除后该调度任务不再自动执行，是否继续？', '删除调度任务', { type: 'warning' }); await api.delete('/report-plans/' + row.id); await load() }
async function runPlan(row: any) { const result: any = await api.post('/report-plans/' + row.id + '/run'); ElMessage.success('已创建执行任务 ' + result.batchId); await load() }
async function transferAction(row: any, action: string) { await api.post('/mock-resumable/sessions/' + row.id + '/' + action); ElMessage.success(action === 'pause' ? '传输已暂停' : action === 'resume' ? '传输已继续' : '已提交失败重试'); await load() }
function progress(row: any) { return row.total_bytes ? Math.min(100, Number((Number(row.uploaded_bytes || 0) / Number(row.total_bytes) * 100).toFixed(1))) : 0 }
watch(() => route.query.tab, () => { active.value = String(route.query.tab || 'plans') })
onMounted(load)
</script>

<template>
  <div v-loading="loading">
    <div class="page-toolbar"><div><h2>医疗数据上报</h2><p>按照设定的时间、周期和优先级，对上报数据进行预审核并完成医疗数据及数字切片上报。</p></div><div class="toolbar-actions"><el-button :icon="Refresh" @click="load">刷新</el-button><el-button v-if="active==='plans'" type="primary" :icon="Plus" @click="openPlan()">新增调度任务</el-button><el-button v-if="active==='cases'&&auth.hasAny(['REPORT_GENERATE'])" type="primary" :icon="Plus" :disabled="!selectedCases.length" @click="openJob">创建上报任务</el-button><el-button v-if="active==='templates'" type="primary" :icon="Plus" @click="openTemplate()">新增报告模板</el-button><el-button v-if="active==='specs'" type="primary" :icon="Plus" @click="openSpec">新增上报平台</el-button></div></div>
    <el-tabs v-model="active" class="tabs-panel">
      <el-tab-pane label="上报任务调度管理" name="plans"><section class="data-panel"><el-table :data="plans"><el-table-column prop="name" label="任务名称" min-width="190"/><el-table-column prop="template_name" label="上报模板" min-width="170"/><el-table-column label="执行周期" width="120"><template #default="{row}">{{frequencyLabel(row.frequency_type)}}</template></el-table-column><el-table-column prop="execution_time" label="执行时间" width="110"/><el-table-column label="优先级" width="90"><template #default="{row}"><el-tag :type="row.priority>=7?'danger':row.priority>=3?'warning':'info'">{{priorityLabel(row.priority)}}</el-tag></template></el-table-column><el-table-column prop="last_run_time" label="上次执行" min-width="170"/><el-table-column prop="next_run_time" label="下次执行" min-width="170"/><el-table-column label="状态" width="90"><template #default="{row}"><el-tag :type="row.enabled?'success':'info'">{{row.enabled?'启用':'停用'}}</el-tag></template></el-table-column><el-table-column label="操作" width="260" fixed="right"><template #default="{row}"><el-button link :icon="VideoPlay" @click="runPlan(row)">立即执行</el-button><el-button link :icon="Edit" @click="openPlan(row)">编辑</el-button><el-button link type="danger" @click="removePlan(row)">停用/删除</el-button></template></el-table-column></el-table></section></el-tab-pane>
      <el-tab-pane label="数据预审核" name="prechecks"><section class="data-panel"><el-alert title="审核不通过的任务会被阻断，不能生成文件或发送；请在问题明细中修改后重新审核。" type="info" show-icon/><el-table :data="prechecks" style="margin-top:12px"><el-table-column prop="id" label="审核任务" width="100"/><el-table-column prop="job_id" label="上报任务" width="100"/><el-table-column prop="status" label="状态" width="110"><template #default="{row}"><el-tag :type="statusType(row.status)">{{statusLabel(row.status)}}</el-tag></template></el-table-column><el-table-column prop="total_count" label="数据量" width="90"/><el-table-column prop="failed_count" label="错误数" width="90"/><el-table-column prop="warning_count" label="警告数" width="90"/><el-table-column prop="finished_at" label="审核时间" min-width="170"/><el-table-column label="操作" width="260"><template #default="{row}"><el-button link type="primary" @click="showIssues(row)">查看问题</el-button><el-button link @click="rerunPrecheck(row)">重新审核</el-button><el-button link v-if="row.status==='PASSED'" type="success" @click="generateJob({id:row.job_id})">生成上报文件</el-button></template></el-table-column></el-table></section></el-tab-pane>
      <el-tab-pane label="安全传输保障" name="transfers"><section class="data-panel"><el-alert title="传输协议：HTTPS　TLS校验：启用　客户端证书：按平台配置　完整性校验：SHA-256" type="success" show-icon/><el-table :data="transfers" style="margin-top:12px"><el-table-column prop="id" label="传输记录" width="100"/><el-table-column prop="total_bytes" label="总大小" width="120"/><el-table-column prop="uploaded_bytes" label="已上传" width="120"/><el-table-column label="传输进度" width="180"><template #default="{row}"><el-progress :percentage="progress(row)" :status="row.status==='FAILED'?'exception':row.status==='SUCCESS'?'success':undefined"/></template></el-table-column><el-table-column label="分片" width="120"><template #default="{row}">{{row.completed_chunks}} / {{row.total_chunks}}</template></el-table-column><el-table-column label="完整性校验" min-width="220"><template #default="{row}"><span class="mono">{{row.whole_sha256 || '完成后生成 SHA-256'}}</span></template></el-table-column><el-table-column label="状态" width="110"><template #default="{row}"><el-tag :type="statusType(row.status)">{{statusLabel(row.status)}}</el-tag></template></el-table-column><el-table-column prop="last_activity_at" label="最后活动" min-width="170"/><el-table-column label="操作" width="210"><template #default="{row}"><el-button link :disabled="row.status!=='UPLOADING'" @click="transferAction(row,'pause')">暂停</el-button><el-button link :disabled="!['PAUSED','INTERRUPTED','FAILED'].includes(row.status)" @click="transferAction(row,'resume')">继续</el-button><el-button link type="danger" :disabled="row.status!=='FAILED'" @click="transferAction(row,'retry')">失败重试</el-button></template></el-table-column></el-table></section></el-tab-pane>
      <el-tab-pane label="多平台上报" name="specs"><section class="data-panel"><el-alert title="根据地方各级卫生健康部门要求配置不同的上报格式、内容和频率。当前内置项标记为示例上报规范，不代表正式卫健委规范。" type="warning" show-icon/><el-table :data="specs" style="margin-top:12px"><el-table-column prop="spec_name" label="上报平台" min-width="200"/><el-table-column prop="authority_name" label="主管部门" min-width="150"/><el-table-column prop="region_code" label="地区" width="100"/><el-table-column prop="version" label="规范版本" width="110"/><el-table-column prop="file_format" label="文件格式" width="100"/><el-table-column prop="default_frequency" label="默认频率" width="110"/><el-table-column prop="transport_mode" label="传输方式" width="110"/><el-table-column prop="enabled" label="状态" width="90"><template #default="{row}"><el-tag :type="row.enabled?'success':'info'">{{row.enabled?'启用':'停用'}}</el-tag></template></el-table-column></el-table></section></el-tab-pane>
      <el-tab-pane label="上报记录" name="batches"><div class="filter-row" style="margin-bottom:12px"><span>演示失败响应</span><el-switch v-model="failMode" :disabled="!auth.hasAny(['REPORT_SEND'])" @change="toggleFail"/></div><section class="data-panel"><el-table :data="batches"><el-table-column prop="batch_no" label="批次号" min-width="190"/><el-table-column prop="report_type" label="上报内容" min-width="145"/><el-table-column prop="format" label="格式" width="80"/><el-table-column prop="total_count" label="数据量" width="85"/><el-table-column label="状态" width="110"><template #default="{row}"><el-tag :type="statusType(row.status)">{{statusLabel(row.status)}}</el-tag></template></el-table-column><el-table-column prop="created_at" label="开始时间" min-width="170"/><el-table-column prop="reported_at" label="结束时间" min-width="170"/><el-table-column prop="success_count" label="成功数量" width="95"/><el-table-column prop="failed_count" label="失败数量" width="95"/><el-table-column prop="last_error" label="失败原因" min-width="220" show-overflow-tooltip/><el-table-column label="操作" width="210" fixed="right"><template #default="{row}"><el-button link @click="details(row)">查看执行记录</el-button><el-button v-if="auth.hasAny(['REPORT_SEND'])&&row.report_job_id" link type="success" :icon="Promotion" :disabled="!['READY','FAILED'].includes(row.status)" @click="sendJob({id:row.report_job_id})">开始上报</el-button><el-button link :icon="Download" :disabled="!row.file_path" @click="download(row)">下载</el-button></template></el-table-column></el-table></section></el-tab-pane>
      <el-tab-pane label="待上报数据" name="cases"><section class="data-panel"><el-table :data="cases" @selection-change="selectedCases=$event"><el-table-column type="selection" width="48"/><el-table-column prop="pathology_no" label="病理号" min-width="150"/><el-table-column prop="patient_name" label="患者" width="110"/><el-table-column prop="specimen_type_code" label="标本类型" width="120"/><el-table-column prop="slide_count" label="切片数量" width="100"/><el-table-column label="质量状态" width="110"><template #default="{row}"><el-tag :type="statusType(row.quality_status)">{{statusLabel(row.quality_status || 'PENDING')}}</el-tag></template></el-table-column><el-table-column label="上报状态" width="110"><template #default="{row}">{{row.report_status==='REPORTED'?'已上报':'待上报'}}</template></el-table-column></el-table></section></el-tab-pane>
      <el-tab-pane v-if="auth.hasAny(['REPORT_GENERATE'])" label="上报任务" name="jobs"><section class="data-panel"><el-table :data="jobs"><el-table-column prop="job_no" label="任务编号" min-width="190"/><el-table-column prop="scheduled_at" label="计划时间" min-width="170"/><el-table-column label="优先级" width="90"><template #default="{row}">{{priorityLabel(row.priority)}}</template></el-table-column><el-table-column label="状态" width="110"><template #default="{row}"><el-tag :type="statusType(row.status)">{{statusLabel(row.status)}}</el-tag></template></el-table-column><el-table-column prop="error_message" label="失败原因" min-width="220" show-overflow-tooltip/><el-table-column label="操作" width="300"><template #default="{row}"><el-button link :disabled="!['WAITING','BLOCKED','FAILED'].includes(row.status)" @click="runPrecheck(row)">预审核</el-button><el-button link type="success" :disabled="row.status!=='READY'" @click="generateJob(row)">生成上报文件</el-button><el-button link type="primary" :disabled="row.status!=='READY'||!auth.hasAny(['REPORT_SEND'])" @click="sendJob(row)">开始上报</el-button></template></el-table-column></el-table></section></el-tab-pane>
      <el-tab-pane v-if="auth.hasAny(['REPORT_GENERATE'])" label="报告模板设置" name="templates"><section class="data-panel"><el-table :data="templates"><el-table-column prop="name" label="模板名称" min-width="220"/><el-table-column prop="report_type" label="报告类型" width="140"/><el-table-column prop="format" label="文件格式" width="100"/><el-table-column label="状态" width="90"><template #default="{row}"><el-tag :type="row.enabled?'success':'info'">{{row.enabled?'启用':'停用'}}</el-tag></template></el-table-column><el-table-column label="操作" width="100"><template #default="{row}"><el-button link :icon="Edit" @click="openTemplate(row)">编辑</el-button></template></el-table-column></el-table></section></el-tab-pane>
    </el-tabs>
    <el-dialog v-model="planDialog" :title="selectedPlan?'编辑上报任务调度':'新增上报任务调度'" width="min(560px,92vw)"><el-form :model="planForm" label-width="100px"><el-form-item label="任务名称"><el-input v-model="planForm.name"/></el-form-item><el-form-item label="上报模板"><el-select v-model="planForm.templateId" style="width:100%"><el-option v-for="x in templates" :key="x.id" :label="x.name" :value="x.id"/></el-select></el-form-item><el-form-item label="上报平台"><el-select v-model="planForm.specId" style="width:100%"><el-option v-for="x in specs" :key="x.id" :label="x.spec_name + '（' + x.version + '）'" :value="x.id"/></el-select></el-form-item><el-row :gutter="14"><el-col :span="12"><el-form-item label="执行周期"><el-select v-model="planForm.frequencyType" style="width:100%"><el-option v-for="x in frequencyOptions" :key="x.value" :label="x.label" :value="x.value"/></el-select></el-form-item></el-col><el-col :span="12"><el-form-item label="执行时间"><el-input v-model="planForm.executionTime" placeholder="如 02:00:00"/></el-form-item></el-col></el-row><el-form-item v-if="planForm.frequencyType==='CRON'" label="自定义周期"><el-input v-model="planForm.cronExpression" placeholder="Spring Cron 6 段表达式"/></el-form-item><el-form-item label="优先级"><el-radio-group v-model="planForm.priority"><el-radio-button v-for="x in priorityOptions" :key="x.value" :label="x.value">{{x.label}}</el-radio-button></el-radio-group></el-form-item><el-form-item label="启用"><el-switch v-model="planForm.enabled"/></el-form-item></el-form><template #footer><el-button @click="planDialog=false">取消</el-button><el-button type="primary" @click="savePlan">保存调度任务</el-button></template></el-dialog>
    <el-dialog v-model="templateDialog" :title="editingTemplateId?'编辑报告模板':'新增报告模板'" width="min(540px,92vw)"><el-form :model="templateForm" label-width="90px"><el-form-item label="模板名称"><el-input v-model="templateForm.name"/></el-form-item><el-form-item label="报告类型"><el-select v-model="templateForm.reportType"><el-option label="病理数据" value="PATHOLOGY"/><el-option label="患者数据" value="PATIENT"/></el-select></el-form-item><el-form-item label="文件格式"><el-select v-model="templateForm.format"><el-option v-for="x in ['JSON','XML','CSV','ZIP']" :key="x" :label="x" :value="x"/></el-select></el-form-item><el-form-item label="包含切片"><el-switch v-model="templateForm.includeSlide"/></el-form-item><el-form-item label="启用"><el-switch v-model="templateForm.enabled"/></el-form-item></el-form><template #footer><el-button @click="templateDialog=false">取消</el-button><el-button type="primary" @click="saveTemplate">保存模板</el-button></template></el-dialog>
    <el-dialog v-model="specDialog" title="新增多平台上报规范" width="min(580px,92vw)"><el-form :model="specForm" label-width="100px"><el-form-item label="平台名称"><el-input v-model="specForm.specName"/></el-form-item><el-form-item label="规范编码"><el-input v-model="specForm.specCode"/></el-form-item><el-row :gutter="14"><el-col :span="12"><el-form-item label="主管部门"><el-input v-model="specForm.authorityName"/></el-form-item></el-col><el-col :span="12"><el-form-item label="地区"><el-input v-model="specForm.regionCode"/></el-form-item></el-col></el-row><el-row :gutter="14"><el-col :span="12"><el-form-item label="规范版本"><el-input v-model="specForm.version"/></el-form-item></el-col><el-col :span="12"><el-form-item label="文件格式"><el-select v-model="specForm.fileFormat"><el-option v-for="x in ['JSON','XML','CSV','ZIP']" :key="x" :label="x" :value="x"/></el-select></el-form-item></el-col></el-row><el-form-item label="示例规范"><el-switch v-model="specForm.demo" active-text="是" inactive-text="否"/></el-form-item></el-form><template #footer><el-button @click="specDialog=false">取消</el-button><el-button type="primary" @click="saveSpec">保存平台规范</el-button></template></el-dialog>
    <el-dialog v-model="issueDialog" title="审核问题明细" width="min(820px,94vw)"><el-table :data="issues"><el-table-column prop="business_id" label="数据对象" width="100"/><el-table-column prop="field_code" label="字段" width="130"/><el-table-column prop="current_value" label="当前值" min-width="140"/><el-table-column prop="severity" label="问题类型" width="100"/><el-table-column prop="error_message" label="错误信息" min-width="220"/><el-table-column prop="suggestion" label="修改建议" min-width="220"/><el-table-column prop="status" label="状态" width="90"><template #default="{row}"><el-tag :type="statusType(row.status)">{{statusLabel(row.status)}}</el-tag></template></el-table-column><el-table-column label="操作" width="130"><template #default="{row}"><el-button link type="primary" :disabled="row.status!=='OPEN'" @click="openIssueEdit(row)">修改</el-button><el-button link :disabled="row.status!=='OPEN'" @click="ignoreIssue(row)">忽略</el-button></template></el-table-column></el-table><template #footer><el-button @click="issueDialog=false">关闭</el-button><el-button type="primary" @click="rerunPrecheck(selectedPrecheck)">重新审核</el-button></template></el-dialog>
    <el-dialog v-model="issueEditDialog" title="修改审核问题" width="min(520px,92vw)"><el-descriptions :column="1" border><el-descriptions-item label="字段">{{selectedIssue?.field_code}}</el-descriptions-item><el-descriptions-item label="错误信息">{{selectedIssue?.error_message}}</el-descriptions-item><el-descriptions-item label="修改建议">{{selectedIssue?.suggestion}}</el-descriptions-item></el-descriptions><el-form label-width="90px" style="margin-top:18px"><el-form-item label="修改值"><el-input v-model="issueForm.newValue"/></el-form-item><el-form-item label="处理说明"><el-input v-model="issueForm.reason" type="textarea" :rows="3"/></el-form-item></el-form><template #footer><el-button @click="issueEditDialog=false">取消</el-button><el-button type="primary" @click="saveIssue">保存并重新审核</el-button></template></el-dialog>
    <el-dialog v-model="detailDialog" :title="'执行记录 · ' + (selected?.batch_no || '')" width="min(780px,94vw)"><el-table :data="records"><el-table-column prop="business_type" label="数据对象"/><el-table-column prop="business_id" label="数据编号"/><el-table-column label="状态"><template #default="{row}"><el-tag :type="statusType(row.status)">{{statusLabel(row.status)}}</el-tag></template></el-table-column><el-table-column prop="error_message" label="失败原因" min-width="260"/></el-table></el-dialog>
    <el-dialog v-model="jobDialog" title="创建上报任务" width="min(480px,92vw)"><el-form label-width="90px"><el-form-item label="上报平台"><el-select v-model="jobForm.specId" style="width:100%"><el-option v-for="x in specs" :key="x.id" :label="x.spec_name" :value="x.id"/></el-select></el-form-item><el-form-item label="计划时间"><el-input v-model="jobForm.scheduledAt" placeholder="留空立即进入预审核"/></el-form-item><el-form-item label="优先级"><el-radio-group v-model="jobForm.priority"><el-radio-button v-for="x in priorityOptions" :key="x.value" :label="x.value">{{x.label}}</el-radio-button></el-radio-group></el-form-item></el-form><template #footer><el-button @click="jobDialog=false">取消</el-button><el-button type="primary" @click="createJob">创建并预审核</el-button></template></el-dialog>
  </div>
</template>
