<script setup lang="ts">
import { nextTick, onBeforeUnmount, onMounted, reactive, ref } from 'vue'
import { Box, Delete, Download, Edit, FullScreen, Plus, Refresh, RefreshRight, Search, View } from '@element-plus/icons-vue'
import { ElMessage, ElMessageBox, type UploadFile } from 'element-plus'
import OpenSeadragon from 'openseadragon'
import api from '../api'
import { useAuthStore } from '../stores/auth'

const auth=useAuthStore();const active=ref('slides');const loading=ref(false);const slides=ref<any[]>([]);const cases=ref<any[]>([]);const adapters=ref<any[]>([]);const targets=ref<any[]>([]);const archiveTasks=ref<any[]>([])
const uploadDialog=ref(false);const viewerDialog=ref(false);const renameDialog=ref(false);const archiveDialog=ref(false);const current=ref<any>();const selectedFile=ref<File>();const uploadForm=reactive<any>({caseId:undefined,slideNo:''});const renameName=ref('');const archiveForm=reactive<any>({targetStorageId:undefined,note:''});const zoom=ref('1.00×');const filters=reactive<any>({pathologyNo:'',patientName:'',slideNo:'',fileName:'',specimenType:'',format:'',archiveStatus:'',storageClass:''});let viewer:OpenSeadragon.Viewer|undefined
function formatBytes(value=0){if(!value)return '0 B';const units=['B','KB','MB','GB','TB'];const i=Math.min(Math.floor(Math.log(value)/Math.log(1024)),4);return `${(value/1024**i).toFixed(i?1:0)} ${units[i]}`}
async function load(){loading.value=true;try{[slides.value,cases.value,adapters.value]=await Promise.all([api.get('/slides',{params:filters}),api.get('/slides/cases'),api.get('/system/adapters')]);if(auth.hasAny(['SLIDE_ARCHIVE']))[targets.value,archiveTasks.value]=await Promise.all([api.get('/storage-targets'),api.get('/archive/tasks')])}finally{loading.value=false}}
function reset(){Object.keys(filters).forEach(key=>filters[key]='');load()}
function openUpload(){uploadForm.caseId=cases.value[0]?.id;uploadForm.slideNo=`SLIDE-${Date.now().toString().slice(-6)}`;selectedFile.value=undefined;uploadDialog.value=true}
function fileChanged(file:UploadFile){selectedFile.value=file.raw}
async function upload(){if(!selectedFile.value){ElMessage.warning('请选择切片文件');return}const data=new FormData();data.append('caseId',String(uploadForm.caseId));data.append('slideNo',uploadForm.slideNo);data.append('file',selectedFile.value);loading.value=true;try{await api.post('/slides/upload',data,{headers:{'Content-Type':'multipart/form-data'},timeout:0});uploadDialog.value=false;ElMessage.success('切片已上传并完成解析')}finally{await load()}}
async function reparse(row:any){try{await api.post(`/slides/${row.id}/analyze`);ElMessage.success('解析完成')}finally{load()}}
function openArchive(row:any){current.value=row;archiveForm.targetStorageId=targets.value.find(x=>x.storage_class==='ARCHIVE')?.id;archiveForm.note='';archiveDialog.value=true}
async function archive(){await api.post(`/slides/${current.value.id}/archive`,archiveForm);archiveDialog.value=false;ElMessage.success('真实归档与 MD5 校验完成');load()}
function openRename(row:any){current.value=row;renameName.value=row.display_name||row.file_name;renameDialog.value=true}
async function rename(){await api.put(`/slides/${current.value.id}/rename`,{displayName:renameName.value});renameDialog.value=false;ElMessage.success('展示名称已更新');load()}
async function remove(row:any){await ElMessageBox.confirm('切片将被逻辑删除，原始对象不会立即物理删除。','确认删除',{type:'warning'});await api.delete(`/slides/${row.id}`);ElMessage.success('切片已逻辑删除');load()}
async function download(row:any){const blob:Blob=await api.get(`/slides/${row.id}/download`,{responseType:'blob'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=row.display_name||row.file_name;a.click();URL.revokeObjectURL(url)}
async function openViewer(row:any){current.value=await api.get(`/slides/${row.id}`);viewerDialog.value=true;await nextTick();initViewer()}
function initViewer(){viewer?.destroy();if(!current.value)return;const token=encodeURIComponent(localStorage.getItem('medical_token')||'');const levels=JSON.parse(current.value.levels_json||'[]').slice().sort((a:any,b:any)=>Number(a.width)-Number(b.width));const maxLevel=Math.max(Number(current.value.level_count||1)-1,0);const tileSize=Number(levels[maxLevel]?.tileSize||256);const tileSource:any={width:Number(current.value.width),height:Number(current.value.height),tileSize,minLevel:0,maxLevel,getTileUrl:(level:number,x:number,y:number)=>`/api/slides/${current.value.id}/tiles/${level}/${x}/${y}?access_token=${token}`,getLevelScale:(level:number)=>levels[level]?.width/Number(current.value.width)||1/Math.pow(2,maxLevel-level)};viewer=OpenSeadragon({id:'slide-viewer-canvas',tileSources:tileSource,prefixUrl:'/openseadragon/images/',showNavigator:true,showFullPageControl:true,showHomeControl:true,showZoomControl:true,navigatorPosition:'BOTTOM_RIGHT',animationTime:.5,blendTime:.1});viewer.addHandler('zoom',()=>{zoom.value=`${viewer?.viewport.getZoom(true).toFixed(2)}×`})}
function statusType(status:string){return status==='READY'?'success':status==='FAILED'?'danger':status==='ARCHIVED'?'info':'warning'}
onBeforeUnmount(()=>viewer?.destroy());onMounted(load)
</script>

<template>
  <div v-loading="loading"><div class="page-toolbar"><div><h2>数字切片管理</h2><p>查询、阅片、下载、归档及全生命周期状态跟踪</p></div><div class="toolbar-actions"><el-button :icon="Refresh" @click="load">刷新</el-button><el-button v-if="auth.hasAny(['SLIDE_UPLOAD'])" type="primary" :icon="Plus" @click="openUpload">上传切片</el-button></div></div>
    <el-tabs v-model="active" class="tabs-panel">
      <el-tab-pane label="切片管理" name="slides"><section class="filter-band"><el-input v-model="filters.pathologyNo" placeholder="病理号" clearable/><el-input v-model="filters.patientName" placeholder="患者姓名" clearable/><el-input v-model="filters.slideNo" placeholder="切片号" clearable/><el-input v-model="filters.fileName" placeholder="文件名称" clearable/><el-select v-model="filters.format" placeholder="切片格式" clearable><el-option v-for="x in ['SVS','TMAP','KFB','TRON','MDSX','SDPC','DMETRIX','FENLAN','ZYP','HWP','CSP']" :key="x" :label="x" :value="x"/></el-select><el-select v-model="filters.archiveStatus" placeholder="归档状态" clearable><el-option label="未归档" value="NOT_ARCHIVED"/><el-option label="成功" value="SUCCESS"/><el-option label="失败" value="FAILED"/></el-select><el-button type="primary" :icon="Search" @click="load">查询</el-button><el-button @click="reset">重置</el-button></section>
        <section class="data-panel"><el-table :data="slides"><el-table-column prop="pathology_no" label="病理号" min-width="130"/><el-table-column prop="patient_name" label="患者" width="100"/><el-table-column prop="specimen_type_code" label="标本类型" width="110"/><el-table-column prop="slide_no" label="切片号" min-width="130"/><el-table-column prop="display_name" label="文件名称" min-width="210" show-overflow-tooltip/><el-table-column prop="file_format" label="格式" width="85"/><el-table-column prop="scan_time" label="扫描时间" min-width="165"/><el-table-column label="大小" width="100"><template #default="{row}">{{formatBytes(row.file_size)}}</template></el-table-column><el-table-column prop="storage_target_name" label="存储位置" min-width="130"/><el-table-column label="归档" width="105"><template #default="{row}"><el-tag effect="plain">{{row.archive_status}}</el-tag></template></el-table-column><el-table-column label="解析" width="100"><template #default="{row}"><el-tag :type="statusType(row.status)">{{row.status}}</el-tag></template></el-table-column><el-table-column label="操作" width="405" fixed="right"><template #default="{row}"><div class="table-actions"><el-button link type="primary" :icon="View" :disabled="!['READY','ARCHIVED'].includes(row.status)" @click="openViewer(row)">阅片</el-button><el-button v-if="auth.hasAny(['SLIDE_DOWNLOAD'])" link :icon="Download" @click="download(row)">下载</el-button><el-button v-if="auth.hasAny(['SLIDE_RENAME'])" link :icon="Edit" @click="openRename(row)">重命名</el-button><el-button v-if="auth.hasAny(['SLIDE_UPLOAD'])" link :icon="RefreshRight" @click="reparse(row)">解析</el-button><el-button v-if="auth.hasAny(['SLIDE_ARCHIVE'])" link :icon="Box" :disabled="row.status!=='READY'" @click="openArchive(row)">归档</el-button><el-button v-if="auth.hasAny(['SLIDE_DELETE'])" link type="danger" :icon="Delete" @click="remove(row)">删除</el-button></div></template></el-table-column></el-table></section></el-tab-pane>
      <el-tab-pane v-if="auth.hasAny(['SLIDE_ARCHIVE'])" label="归档任务" name="archive"><section class="data-panel"><el-table :data="archiveTasks"><el-table-column prop="slide_no" label="切片号" min-width="140"/><el-table-column prop="display_name" label="文件" min-width="200"/><el-table-column prop="target_name" label="归档目标" min-width="150"/><el-table-column label="进度" width="180"><template #default="{row}"><el-progress :percentage="row.progress" :status="row.status==='FAILED'?'exception':row.status==='SUCCESS'?'success':undefined"/></template></el-table-column><el-table-column prop="source_md5" label="源 MD5" min-width="210"/><el-table-column prop="target_md5" label="目标 MD5" min-width="210"/><el-table-column prop="operator" label="操作人" width="100"/><el-table-column prop="created_at" label="时间" min-width="170"/><el-table-column prop="error_message" label="错误" min-width="220" show-overflow-tooltip/></el-table></section></el-tab-pane>
      <el-tab-pane label="格式适配" name="adapters"><section class="data-panel"><el-table :data="adapters"><el-table-column prop="format" label="格式" width="110"/><el-table-column prop="engine" label="解析引擎" min-width="150"/><el-table-column label="扩展名" min-width="130"><template #default="{row}"><span class="mono">{{row.extensions?.join(', ')}}</span></template></el-table-column><el-table-column label="能力状态" min-width="180"><template #default="{row}"><el-tag :type="row.sdkStatus==='AVAILABLE'?'success':row.sdkStatus==='SDK_REQUIRED'||row.sdkStatus==='PARSER_UNAVAILABLE'?'danger':'warning'">{{row.sdkStatus}}</el-tag></template></el-table-column><el-table-column label="已实测" width="90"><template #default="{row}">{{row.tested?'是':'否'}}</template></el-table-column><el-table-column prop="missingDependency" label="缺少依赖" min-width="240" show-overflow-tooltip/></el-table></section></el-tab-pane>
    </el-tabs>
    <el-dialog v-model="uploadDialog" title="上传数字病理切片" width="min(540px,92vw)"><el-form :model="uploadForm" label-width="82px"><el-form-item label="病理病例"><el-select v-model="uploadForm.caseId" style="width:100%"><el-option v-for="x in cases" :key="x.id" :label="`${x.pathology_no} · ${x.specimen_name}`" :value="x.id"/></el-select></el-form-item><el-form-item label="切片号"><el-input v-model="uploadForm.slideNo"/></el-form-item><el-form-item label="切片文件"><el-upload drag :auto-upload="false" :limit="1" accept=".svs,.tmap,.kfb,.tron,.mdsx,.sdpc,.dmetrix,.fenlan,.zyp,.hwp,.csp" :on-change="fileChanged"><el-icon><Plus/></el-icon><div>选择切片文件</div></el-upload></el-form-item></el-form><template #footer><el-button @click="uploadDialog=false">取消</el-button><el-button type="primary" @click="upload">上传并解析</el-button></template></el-dialog>
    <el-dialog v-model="renameDialog" title="修改展示名称" width="min(440px,92vw)"><el-input v-model="renameName"/><template #footer><el-button @click="renameDialog=false">取消</el-button><el-button type="primary" @click="rename">保存</el-button></template></el-dialog>
    <el-dialog v-model="archiveDialog" title="归档切片" width="min(480px,92vw)"><el-form :model="archiveForm" label-width="86px"><el-form-item label="归档目标"><el-select v-model="archiveForm.targetStorageId" style="width:100%"><el-option v-for="x in targets.filter(x=>x.storage_class==='ARCHIVE')" :key="x.id" :label="`${x.name} · ${x.bucket}`" :value="x.id"/></el-select></el-form-item><el-form-item label="备注"><el-input v-model="archiveForm.note" type="textarea"/></el-form-item></el-form><template #footer><el-button @click="archiveDialog=false">取消</el-button><el-button type="primary" @click="archive">确认归档</el-button></template></el-dialog>
    <el-dialog v-model="viewerDialog" class="viewer-dialog" width="min(1180px,96vw)" top="4vh" destroy-on-close @closed="viewer?.destroy()"><template #header><div style="display:flex;align-items:center;gap:10px"><el-icon><FullScreen/></el-icon><strong>{{current?.slide_no}} · {{current?.display_name}}</strong><el-tag size="small" type="success">{{zoom}}</el-tag></div></template><div class="slide-viewer"><div id="slide-viewer-canvas" class="viewer-canvas"></div><aside class="viewer-info"><h3>切片信息</h3><dl><dt>格式</dt><dd>{{current?.file_format}}</dd><dt>Adapter</dt><dd>{{current?.adapter_type}}</dd><dt>尺寸</dt><dd>{{current?.width}} × {{current?.height}} px</dd><dt>层级</dt><dd>{{current?.level_count}}</dd><dt>MD5</dt><dd class="mono">{{current?.md5}}</dd><dt>对象路径</dt><dd class="mono">{{current?.object_key}}</dd></dl></aside></div></el-dialog>
  </div>
</template>
