<script setup lang="ts">
import { nextTick, onBeforeUnmount, onMounted, reactive, ref } from 'vue'
import { Box, FullScreen, Plus, Refresh, RefreshRight, View } from '@element-plus/icons-vue'
import { ElMessage, type UploadFile } from 'element-plus'
import OpenSeadragon from 'openseadragon'
import api from '../api'

const loading=ref(false); const slides=ref<any[]>([]); const cases=ref<any[]>([]); const adapters=ref<any[]>([]); const uploadDialog=ref(false); const viewerDialog=ref(false); const current=ref<any>(); const selectedFile=ref<File>(); const uploadForm=reactive<any>({caseId:undefined,slideNo:''}); const zoom=ref('1.00×'); let viewer:OpenSeadragon.Viewer|undefined
function formatBytes(value=0){if(!value)return '0 B';const units=['B','KB','MB','GB','TB'];const i=Math.min(Math.floor(Math.log(value)/Math.log(1024)),4);return `${(value/1024**i).toFixed(i?1:0)} ${units[i]}`}
async function load(){loading.value=true;try{[slides.value,cases.value,adapters.value]=await Promise.all([api.get('/slides'),api.get('/slides/cases'),api.get('/system/adapters')])}finally{loading.value=false}}
function openUpload(){uploadForm.caseId=cases.value[0]?.id;uploadForm.slideNo=`SLIDE-${Date.now().toString().slice(-6)}`;selectedFile.value=undefined;uploadDialog.value=true}
function fileChanged(file:UploadFile){selectedFile.value=file.raw}
async function upload(){if(!selectedFile.value){ElMessage.warning('请选择切片文件');return}const data=new FormData();data.append('caseId',String(uploadForm.caseId));data.append('slideNo',uploadForm.slideNo);data.append('file',selectedFile.value);loading.value=true;try{await api.post('/slides/upload',data,{headers:{'Content-Type':'multipart/form-data'},timeout:0});uploadDialog.value=false;ElMessage.success('切片已上传并完成解析')}finally{await load()}}
async function reparse(row:any){try{await api.post(`/slides/${row.id}/analyze`);ElMessage.success('解析完成')}finally{load()}}
async function archive(row:any){await api.post(`/slides/${row.id}/archive`);ElMessage.success('切片已归档');load()}
async function openViewer(row:any){current.value=await api.get(`/slides/${row.id}`);viewerDialog.value=true;await nextTick();initViewer()}
function initViewer(){viewer?.destroy();if(!current.value)return;const token=encodeURIComponent(localStorage.getItem('medical_token')||'');const levels=JSON.parse(current.value.levels_json||'[]').slice().reverse();const maxLevel=Math.max(Number(current.value.level_count||1)-1,0);const tileSource:any={width:Number(current.value.width),height:Number(current.value.height),tileSize:256,minLevel:0,maxLevel,getTileUrl:(level:number,x:number,y:number)=>`/api/slides/${current.value.id}/tiles/${level}/${x}/${y}?access_token=${token}`,getLevelScale:(level:number)=>levels[level]?.width/Number(current.value.width)||1/Math.pow(2,maxLevel-level)};viewer=OpenSeadragon({id:'slide-viewer-canvas',tileSources:tileSource,prefixUrl:'/openseadragon/images/',showNavigator:true,showFullPageControl:true,showHomeControl:true,showZoomControl:true,navigatorPosition:'BOTTOM_RIGHT',animationTime:.5,blendTime:.1});viewer.addHandler('zoom',()=>{zoom.value=`${viewer?.viewport.getZoom(true).toFixed(2)}×`})}
function statusType(status:string){return status==='READY'?'success':status==='FAILED'?'danger':status==='ARCHIVED'?'info':'warning'}
onBeforeUnmount(()=>viewer?.destroy());onMounted(load)
</script>

<template>
  <div v-loading="loading"><div class="page-toolbar"><div><h2>病理切片库</h2><p>对象存储、格式适配、元数据解析与在线阅片</p></div><div class="toolbar-actions"><el-button :icon="Refresh" @click="load">刷新</el-button><el-button type="primary" :icon="Plus" @click="openUpload">上传切片</el-button></div></div>
    <section class="data-panel"><el-table :data="slides"><el-table-column prop="pathology_no" label="病理号" min-width="130"/><el-table-column prop="patient_name" label="患者" width="100"><template #default="{row}">{{row.patient_name||'-'}}</template></el-table-column><el-table-column prop="slide_no" label="切片号" min-width="130"/><el-table-column prop="file_name" label="文件名称" min-width="210" show-overflow-tooltip/><el-table-column prop="file_format" label="格式" width="90"/><el-table-column label="文件大小" width="110"><template #default="{row}">{{formatBytes(row.file_size)}}</template></el-table-column><el-table-column label="解析能力" width="130"><template #default="{row}"><el-tag :type="row.sdk_status==='AVAILABLE'?'success':'warning'" effect="plain">{{row.sdk_status}}</el-tag></template></el-table-column><el-table-column label="状态" width="100"><template #default="{row}"><el-tag :type="statusType(row.status)">{{row.status}}</el-tag></template></el-table-column><el-table-column prop="created_at" label="上传时间" min-width="170"/><el-table-column label="操作" width="235" fixed="right"><template #default="{row}"><div class="table-actions"><el-button link type="primary" :icon="View" :disabled="row.status!=='READY'" @click="openViewer(row)">查看</el-button><el-button link :icon="RefreshRight" @click="reparse(row)">重新解析</el-button><el-button link :icon="Box" :disabled="row.status!=='READY'" @click="archive(row)">归档</el-button><el-tooltip v-if="row.error_message" :content="row.error_message"><el-button link type="danger">异常</el-button></el-tooltip></div></template></el-table-column></el-table></section>
    <section class="data-panel" style="margin-top:18px"><div class="data-panel-header"><strong>格式适配能力</strong><small>实际能力以 SDK 状态为准</small></div><el-table :data="adapters" size="small"><el-table-column prop="adapterType" label="Adapter" min-width="160"/><el-table-column label="扩展名" min-width="220"><template #default="{row}"><span class="mono">{{row.extensions?.join(', ')}}</span></template></el-table-column><el-table-column label="SDK 状态" width="160"><template #default="{row}"><el-tag :type="row.sdkStatus==='AVAILABLE'?'success':'warning'">{{row.sdkStatus}}</el-tag></template></el-table-column></el-table></section>
    <el-dialog v-model="uploadDialog" title="上传数字病理切片" width="min(540px,92vw)"><el-form :model="uploadForm" label-width="82px"><el-form-item label="病理病例"><el-select v-model="uploadForm.caseId" style="width:100%"><el-option v-for="x in cases" :key="x.id" :label="`${x.pathology_no} · ${x.specimen_name}`" :value="x.id"/></el-select></el-form-item><el-form-item label="切片号"><el-input v-model="uploadForm.slideNo"/></el-form-item><el-form-item label="切片文件"><el-upload drag :auto-upload="false" :limit="1" accept=".svs,.tmap,.kfb,.tron,.mdsx,.sdpc,.dmetrix,.fenlan,.zyp,.hwp,.csp" :on-change="fileChanged"><el-icon size="28"><Plus/></el-icon><div>拖放文件到此处，或点击选择</div><template #tip><div class="el-upload__tip">SVS 可真实解析；厂家格式需对应 SDK</div></template></el-upload></el-form-item></el-form><template #footer><el-button @click="uploadDialog=false">取消</el-button><el-button type="primary" @click="upload">上传并解析</el-button></template></el-dialog>
    <el-dialog v-model="viewerDialog" class="viewer-dialog" width="min(1180px,96vw)" top="4vh" destroy-on-close @closed="viewer?.destroy()"><template #header><div style="display:flex;align-items:center;gap:10px"><el-icon><FullScreen/></el-icon><strong>{{current?.slide_no}} · {{current?.file_name}}</strong><el-tag size="small" type="success">{{zoom}}</el-tag></div></template><div class="slide-viewer"><div id="slide-viewer-canvas" class="viewer-canvas"></div><aside class="viewer-info"><h3>切片信息</h3><dl><dt>格式</dt><dd>{{current?.file_format}}</dd><dt>Adapter</dt><dd>{{current?.adapter_type}}</dd><dt>尺寸</dt><dd>{{current?.width}} × {{current?.height}} px</dd><dt>层级</dt><dd>{{current?.level_count}}</dd><dt>文件大小</dt><dd>{{formatBytes(current?.file_size)}}</dd><dt>MD5</dt><dd class="mono">{{current?.md5}}</dd><dt>对象路径</dt><dd class="mono">{{current?.object_key}}</dd></dl></aside></div></el-dialog>
  </div>
</template>
