<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { Plus, Refresh } from '@element-plus/icons-vue'
import { ElMessage } from 'element-plus'
import api from '../api'

const active=ref('monitor');const loading=ref(false);const health=ref<any>({components:{},queues:{}});const users=ref<any[]>([]);const configs=ref<any[]>([]);const logs=ref<any[]>([]);const adapters=ref<any[]>([]);const userDialog=ref(false);const editingId=ref<number>();const userForm=reactive<any>({username:'',displayName:'',password:'',role:'USER',enabled:true});const configDialog=ref(false);const configForm=reactive<any>({id:0,configKey:'',configValue:'',description:''})
const queueLabels:Record<string,string>={pendingCollectTasks:'待执行采集任务',failedCollectTasks:'失败采集任务',pendingSlides:'待处理切片',failedSlides:'失败切片',pendingReports:'待上报批次',failedReports:'失败上报批次'}
async function load(){loading.value=true;try{[health.value,users.value,configs.value,logs.value,adapters.value]=await Promise.all([api.get('/system/health'),api.get('/system/users'),api.get('/system/configs'),api.get('/system/operation-logs'),api.get('/system/adapters')])}finally{loading.value=false}}
function addUser(){editingId.value=undefined;Object.assign(userForm,{username:'',displayName:'',password:'',role:'USER',enabled:true});userDialog.value=true}
function editUser(row:any){editingId.value=row.id;Object.assign(userForm,{username:row.username,displayName:row.display_name,password:'',role:row.role,enabled:!!row.enabled});userDialog.value=true}
async function saveUser(){if(editingId.value)await api.put(`/system/users/${editingId.value}`,userForm);else await api.post('/system/users',userForm);userDialog.value=false;ElMessage.success('用户已保存');load()}
function editConfig(row:any){Object.assign(configForm,{id:row.id,configKey:row.config_key,configValue:row.config_value,description:row.description});configDialog.value=true}
async function saveConfig(){await api.put(`/system/configs/${configForm.id}`,configForm);configDialog.value=false;ElMessage.success('配置已更新');load()}
function componentLabel(key:string){return {mysql:'MySQL',minio:'MinIO',slideWorker:'Slide Worker'}[key]||key}
onMounted(load)
</script>

<template>
  <div v-loading="loading"><div class="page-toolbar"><div><h2>平台配置与运行审计</h2><p>维护基础账号与配置，查看服务健康和业务操作记录</p></div><div class="toolbar-actions"><el-button :icon="Refresh" @click="load">刷新</el-button><el-button v-if="active==='users'" type="primary" :icon="Plus" @click="addUser">新增用户</el-button></div></div>
    <el-tabs v-model="active" class="tabs-panel">
      <el-tab-pane label="系统监控" name="monitor"><div class="dashboard-grid"><section class="data-panel"><div class="data-panel-header"><strong>基础服务</strong><small>Health Check</small></div><div class="health-list"><div v-for="(item,key) in health.components" :key="key" class="health-item"><label>{{componentLabel(String(key))}}</label><span class="status-dot" :class="String(item.status).toLowerCase()">{{item.status}}</span></div></div></section><section class="data-panel"><div class="data-panel-header"><strong>业务队列</strong><small>当前数量</small></div><div class="storage-lines"><div v-for="(value,key) in health.queues" :key="key" class="storage-line"><span>{{queueLabels[String(key)]}}</span><strong>{{value}}</strong></div></div></section></div></el-tab-pane>
      <el-tab-pane label="用户管理" name="users"><section class="data-panel"><el-table :data="users"><el-table-column prop="username" label="用户名" min-width="130"/><el-table-column prop="display_name" label="姓名" min-width="130"/><el-table-column prop="role" label="角色" width="100"/><el-table-column label="状态" width="90"><template #default="{row}"><el-tag :type="row.enabled?'success':'info'">{{row.enabled?'启用':'停用'}}</el-tag></template></el-table-column><el-table-column prop="updated_at" label="更新时间" min-width="170"/><el-table-column label="操作" width="90"><template #default="{row}"><el-button link type="primary" @click="editUser(row)">编辑</el-button></template></el-table-column></el-table></section></el-tab-pane>
      <el-tab-pane label="基础配置" name="config"><section class="data-panel"><el-table :data="configs"><el-table-column prop="config_key" label="配置项" min-width="220"/><el-table-column prop="config_value" label="配置值" min-width="220"/><el-table-column prop="description" label="说明" min-width="250"/><el-table-column label="操作" width="90"><template #default="{row}"><el-button link type="primary" @click="editConfig(row)">编辑</el-button></template></el-table-column></el-table></section></el-tab-pane>
      <el-tab-pane label="切片 Adapter" name="adapters"><section class="data-panel"><el-table :data="adapters"><el-table-column prop="adapterType" label="Adapter" min-width="180"/><el-table-column label="识别扩展名" min-width="260"><template #default="{row}"><span class="mono">{{row.extensions?.join(', ')}}</span></template></el-table-column><el-table-column label="能力状态" width="170"><template #default="{row}"><el-tag :type="row.sdkStatus==='AVAILABLE'?'success':'warning'">{{row.sdkStatus}}</el-tag></template></el-table-column></el-table></section></el-tab-pane>
      <el-tab-pane label="操作日志" name="logs"><section class="data-panel"><el-table :data="logs"><el-table-column prop="username" label="用户" width="110"/><el-table-column prop="operation" label="操作" min-width="150"/><el-table-column prop="module" label="模块" width="120"/><el-table-column prop="business_id" label="业务ID" width="100"/><el-table-column prop="created_at" label="时间" min-width="170"/><el-table-column label="结果" width="90"><template #default="{row}"><el-tag :type="row.result==='SUCCESS'?'success':'danger'">{{row.result}}</el-tag></template></el-table-column><el-table-column prop="detail" label="详情" min-width="240" show-overflow-tooltip/></el-table></section></el-tab-pane>
    </el-tabs>
    <el-dialog v-model="userDialog" :title="editingId?'编辑用户':'新增用户'" width="min(480px,92vw)"><el-form :model="userForm" label-width="80px"><el-form-item label="用户名"><el-input v-model="userForm.username" :disabled="!!editingId"/></el-form-item><el-form-item label="姓名"><el-input v-model="userForm.displayName"/></el-form-item><el-form-item label="密码"><el-input v-model="userForm.password" type="password" show-password :placeholder="editingId?'留空表示不修改':'至少 8 位'"/></el-form-item><el-form-item label="角色"><el-segmented v-model="userForm.role" :options="['ADMIN','USER']"/></el-form-item><el-form-item label="启用"><el-switch v-model="userForm.enabled"/></el-form-item></el-form><template #footer><el-button @click="userDialog=false">取消</el-button><el-button type="primary" @click="saveUser">保存</el-button></template></el-dialog>
    <el-dialog v-model="configDialog" title="编辑基础配置" width="min(480px,92vw)"><el-form :model="configForm" label-width="80px"><el-form-item label="配置项"><el-input v-model="configForm.configKey" disabled/></el-form-item><el-form-item label="配置值"><el-input v-model="configForm.configValue"/></el-form-item><el-form-item label="说明"><el-input v-model="configForm.description" type="textarea" :rows="3"/></el-form-item></el-form><template #footer><el-button @click="configDialog=false">取消</el-button><el-button type="primary" @click="saveConfig">保存</el-button></template></el-dialog>
  </div>
</template>
