<script setup lang="ts">
import { computed, onMounted, reactive, ref, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { Check, Close, Connection, Download, Edit, Plus, Refresh, Upload } from '@element-plus/icons-vue'
import { ElMessage, ElMessageBox, type UploadFile } from 'element-plus'
import api from '../api'
import { useAuthStore } from '../stores/auth'

const auth=useAuthStore();const route=useRoute();const router=useRouter();const initialTab=String(route.query.tab||'');const active=ref(initialTab==='alerts'?'alerts':initialTab==='pathology-rules'?'pathology-rules':initialTab==='quality'?'quality':initialTab==='users'?'users':initialTab==='roles'?'roles':initialTab==='logs'?'logs':initialTab==='basic'?'basic':initialTab==='resources'?'monitor':auth.hasAny(['MONITOR_VIEW'])?'monitor':auth.hasAny(['USER_MANAGE'])?'users':'config');const loading=ref(false)
const health=ref<any>({components:{},queues:{}});const metrics=ref<any>({cpu:{},memory:{},disk:{},jvmHeap:{},storageTargets:[],tasks:{}});const users=ref<any[]>([]);const roles=ref<any[]>([]);const permissions=ref<any[]>([]);const configs=ref<any[]>([]);const logs=ref<any[]>([]);const dictionaries=ref<any[]>([]);const dictionaryItems=ref<any[]>([]);const targets=ref<any[]>([]);const alertEvents=ref<any[]>([]);const alertRules=ref<any[]>([]);const pathologyRules=ref<any[]>([]);const qualityIssues=ref<any[]>([])
const userDialog=ref(false);const editingId=ref<number>();const userForm=reactive<any>({username:'',displayName:'',password:'',role:'VIEWER',enabled:true});const roleDialog=ref(false);const roleForm=reactive<any>({id:0,name:'',permissions:[] as string[]});const configDialog=ref(false);const configForm=reactive<any>({id:0,configKey:'',configValue:'',description:''});const itemDialog=ref(false);const itemForm=reactive<any>({id:undefined,dictionaryId:undefined,sourceValue:'',targetValue:'',description:'',enabled:true});const selectedDictionary=ref<number>();const importFormat=ref('CSV');const storageDialog=ref(false);const storageForm=reactive<any>({id:undefined,name:'',storageType:'S3',endpoint:'http://minio:9000',accessKey:'',secretKey:'',bucket:'',basePath:'',storageClass:'HOT',enabled:true});const pathologyRuleDialog=ref(false);const editingPathologyRuleId=ref<number>();const pathologyRuleForm=reactive<any>({name:'常规病理',businessType:'PATHOLOGY_CASE',prefix:'P',yearFormat:'yyyy',separator:'-',sequenceDigits:6,startSequence:1,enabled:true})
const roleCodes=computed(()=>roles.value.map(x=>x.role_code));const visibleItems=computed(()=>dictionaryItems.value.filter(x=>!selectedDictionary.value||x.dictionary_id===selectedDictionary.value));
const visibleAlertEvents=computed(()=>{const types=String(route.query.eventType||'').split(',').filter(Boolean);const sourceId=String(route.query.sourceId||'');return alertEvents.value.filter(row=>(!types.length||types.includes(row.event_type))&&(!sourceId||String(row.source_id)===sourceId))});
async function load(){loading.value=true;try{const jobs:Promise<any>[]=[];if(auth.hasAny(['MONITOR_VIEW']))jobs.push(Promise.all([api.get('/system/health'),api.get('/system/metrics'),api.get('/alerts/events'),api.get('/alerts/rules')]).then(([h,m,e,r])=>{health.value=h;metrics.value=m;alertEvents.value=e;alertRules.value=r}));if(auth.hasAny(['USER_MANAGE']))jobs.push(Promise.all([api.get('/system/users'),api.get('/system/roles'),api.get('/system/permissions')]).then(([u,r,p])=>{users.value=u;roles.value=r;permissions.value=p}));if(auth.hasAny(['SYSTEM_CONFIG']))jobs.push(Promise.all([api.get('/system/configs'),api.get('/storage-targets')]).then(([c,t])=>{configs.value=c;targets.value=t}));if(auth.hasAny(['LOG_VIEW']))jobs.push(api.get('/system/operation-logs').then((x:any)=>logs.value=x));if(auth.hasAny(['DICT_MANAGE']))jobs.push(Promise.all([api.get('/governance/dictionaries'),api.get('/governance/dictionary-items'),api.get('/pathology-number-rules')]).then(([d,i,r])=>{dictionaries.value=d;dictionaryItems.value=i;pathologyRules.value=r;if(!selectedDictionary.value)selectedDictionary.value=d[0]?.id}));if(auth.hasAny(['QUALITY_MANAGE']))jobs.push(api.get('/validation-errors').then((x:any)=>qualityIssues.value=x));await Promise.all(jobs)}finally{loading.value=false}}
function addUser(){editingId.value=undefined;Object.assign(userForm,{username:'',displayName:'',password:'',role:roleCodes.value[0]||'VIEWER',enabled:true});userDialog.value=true}
function editUser(row:any){editingId.value=row.id;Object.assign(userForm,{username:row.username,displayName:row.display_name,password:'',role:row.role,enabled:!!row.enabled});userDialog.value=true}
async function saveUser(){if(editingId.value)await api.put(`/system/users/${editingId.value}`,userForm);else await api.post('/system/users',userForm);userDialog.value=false;ElMessage.success('用户已保存');load()}
function editRole(row:any){Object.assign(roleForm,{id:row.id,name:row.role_name,permissions:[...row.permissions]});roleDialog.value=true}
async function saveRole(){await api.put(`/system/roles/${roleForm.id}/permissions`,{permissions:roleForm.permissions});roleDialog.value=false;ElMessage.success('角色权限已更新');load()}
function editConfig(row:any){Object.assign(configForm,{id:row.id,configKey:row.config_key,configValue:row.config_value,description:row.description});configDialog.value=true}
async function saveConfig(){await api.put(`/system/configs/${configForm.id}`,configForm);configDialog.value=false;ElMessage.success('配置已更新');load()}
function addItem(){Object.assign(itemForm,{id:undefined,dictionaryId:selectedDictionary.value,sourceValue:'',targetValue:'',description:'',enabled:true});itemDialog.value=true}
function editItem(row:any){Object.assign(itemForm,{id:row.id,dictionaryId:row.dictionary_id,sourceValue:row.source_value,targetValue:row.target_value,description:row.description,enabled:!!row.enabled});itemDialog.value=true}
async function saveItem(){const url=`/governance/dictionary-items${itemForm.id?`/${itemForm.id}`:''}`;if(itemForm.id)await api.put(url,itemForm);else await api.post(url,itemForm);itemDialog.value=false;ElMessage.success('基础数据已保存');load()}
async function removeItem(row:any){await ElMessageBox.confirm('确认删除该基础数据项？','删除',{type:'warning'});await api.delete(`/governance/dictionary-items/${row.id}`);load()}
function dictionaryType(){return dictionaries.value.find(x=>x.id===selectedDictionary.value)?.dict_type||''}
async function exportData(format:string){const blob:Blob=await api.get(`/basic-data/export/${dictionaryType()}`,{params:{format},responseType:'blob'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`${dictionaryType()}.${format.toLowerCase()}`;a.click();URL.revokeObjectURL(url)}
async function importData(file:UploadFile){if(!file.raw)return;const data=new FormData();data.append('file',file.raw);const result:any=await api.post(`/basic-data/import/${dictionaryType()}?format=${importFormat.value}`,data,{headers:{'Content-Type':'multipart/form-data'}});ElMessage.success(`成功 ${result.successCount} 行，失败 ${result.errorCount} 行`);if(result.errors?.length)ElMessageBox.alert(result.errors.map((x:any)=>`第 ${x.row} 行：${x.reason}`).join('\n'),'导入错误');load()}
function addStorage(){Object.assign(storageForm,{id:undefined,name:'',storageType:'S3',endpoint:'http://minio:9000',accessKey:'',secretKey:'',bucket:'',basePath:'',storageClass:'HOT',enabled:true});storageDialog.value=true}
function editStorage(row:any){Object.assign(storageForm,{id:row.id,name:row.name,storageType:row.storage_type,endpoint:row.endpoint,accessKey:'',secretKey:'',bucket:row.bucket,basePath:row.base_path,storageClass:row.storage_class,enabled:!!row.enabled});storageDialog.value=true}
async function saveStorage(){if(storageForm.id)await api.put(`/storage-targets/${storageForm.id}`,storageForm);else await api.post('/storage-targets',storageForm);storageDialog.value=false;ElMessage.success('存储目标已保存');load()}
async function testStorage(row:any){const result:any=await api.post(`/storage-targets/${row.id}/test`);ElMessage.success(`${result.bucket} 连接正常`)}
function openPathologyRule(row?:any){editingPathologyRuleId.value=row?.id;Object.assign(pathologyRuleForm,row?{name:row.name,businessType:row.business_type,prefix:row.prefix||'',yearFormat:row.year_format||'yyyy',separator:row.separator||'-',sequenceDigits:row.sequence_digits||6,startSequence:row.start_sequence||1,enabled:!!row.enabled}:{name:'常规病理',businessType:'PATHOLOGY_CASE',prefix:'P',yearFormat:'yyyy',separator:'-',sequenceDigits:6,startSequence:1,enabled:true});pathologyRuleDialog.value=true}
async function savePathologyRule(){const url=`/pathology-number-rules${editingPathologyRuleId.value?`/${editingPathologyRuleId.value}`:''}`;if(editingPathologyRuleId.value)await api.put(url,pathologyRuleForm);else await api.post(url,pathologyRuleForm);pathologyRuleDialog.value=false;ElMessage.success('病理号规则已保存');load()}
async function removePathologyRule(row:any){await ElMessageBox.confirm('删除后该规则不再用于病理号预览，是否继续？','删除病理号规则',{type:'warning'});await api.delete(`/pathology-number-rules/${row.id}`);load()}
async function previewPathologyRule(row:any){const result:any=await api.post(`/pathology-number-rules/${row.id}/preview`);ElMessage.success(`示例：${result.example}`)}
async function alertAction(row:any,action:string){await api.post(`/alerts/events/${row.id}/${action}`);ElMessage.success(action==='close'?'告警已关闭':'告警已确认');load()}
function formatBytes(value:any){if(typeof value!=='number')return value??'UNKNOWN';const units=['B','KB','MB','GB','TB'];if(!value)return '0 B';const i=Math.min(Math.floor(Math.log(value)/Math.log(1024)),4);return `${(value/1024**i).toFixed(i?1:0)} ${units[i]}`}
function componentLabel(key:string){return {mysql:'MySQL',minio:'MinIO',slideWorker:'Slide Worker',goParser:'Go Parser'}[key]||key}
function componentAlertType(key:string){return {mysql:'MYSQL_DOWN',minio:'MINIO_DOWN',slideWorker:'SLIDE_WORKER_DOWN',goParser:'GO_PARSER_DOWN'}[key]||''}
function taskAlertType(key:string){return {collect:'COLLECT_FAILED,COLLECT_STUCK',slide:'SLIDE_PARSE_FAILED,SLIDE_PARSE_STUCK',archive:'ARCHIVE_FAILED,ARCHIVE_STUCK',backup:'BACKUP_FAILED,BACKUP_STUCK',report:'REPORT_FAILED,REPORT_STUCK'}[key]||''}
function queueAlertType(key:string){return {pendingCollectTasks:'COLLECT_QUEUE_BACKLOG',pendingSlides:'SLIDE_QUEUE_BACKLOG',pendingReports:'REPORT_QUEUE_BACKLOG',pendingArchiveTasks:'ARCHIVE_QUEUE_BACKLOG',pendingBackupTasks:'BACKUP_QUEUE_BACKLOG'}[key]||''}
function openAlerts(eventType:string){active.value='alerts';router.replace({query:{...route.query,tab:'alerts',eventType}})}
function openStorageAlerts(row:any){active.value='alerts';router.replace({query:{...route.query,tab:'alerts',eventType:'STORAGE_TARGET_DOWN,STORAGE_READ_FAILED,STORAGE_WRITE_FAILED,STORAGE_USAGE_HIGH',sourceId:String(row.id)}})}
watch(()=>route.query.tab,(tab)=>{if(tab==='alerts'&&auth.hasAny(['MONITOR_VIEW']))active.value='alerts';else if(tab==='resources')active.value='monitor';else if(tab)active.value=String(tab)})
onMounted(load)
</script>

<template>
  <div v-loading="loading"><div class="page-toolbar"><div><h2>系统管理</h2><p>集中管理用户、权限、日志、运行资源和质量控制。</p></div><div class="toolbar-actions"><el-button :icon="Refresh" @click="load">刷新</el-button><el-button v-if="active==='users'" type="primary" :icon="Plus" @click="addUser">新增用户</el-button><el-button v-if="active==='basic'" type="primary" :icon="Plus" @click="addItem">新增标本类型</el-button><el-button v-if="active==='pathology-rules'" type="primary" :icon="Plus" @click="openPathologyRule()">新增病理号规则</el-button><el-button v-if="active==='storage'" type="primary" :icon="Plus" @click="addStorage">新增存储目标</el-button></div></div>
    <el-tabs v-model="active" class="tabs-panel">
      <el-tab-pane v-if="auth.hasAny(['MONITOR_VIEW'])" label="资源管理" name="monitor"><div class="metric-grid"><section v-for="(entry,key) in {CPU:{value:metrics.cpu,type:'CPU_USAGE_HIGH'},内存:{value:metrics.memory,type:'MEMORY_USAGE_HIGH'},磁盘:{value:metrics.disk,type:'DISK_USAGE_HIGH'},'JVM Heap':{value:metrics.jvmHeap,type:'JVM_HEAP_USAGE_HIGH'}}" :key="key" class="metric-cell monitor-link" role="button" @click="openAlerts(entry.type)"><span>{{key}}</span><strong>{{entry.value.usagePercent}}%</strong><small v-if="entry.value.usedBytes">{{formatBytes(entry.value.usedBytes)}} / {{formatBytes(entry.value.totalBytes||entry.value.maxBytes)}}</small></section></div><div class="dashboard-grid"><section class="data-panel"><div class="data-panel-header"><strong>基础服务</strong><small>运行状态</small></div><div class="health-list"><div v-for="(item,key) in health.components" :key="key" class="health-item monitor-link" role="button" @click="openAlerts(componentAlertType(String(key)))"><label>{{componentLabel(String(key))}}</label><span class="status-dot" :class="String(item.status).toLowerCase()">{{item.status==='UP'?'正常':'异常'}}</span></div></div></section><section class="data-panel"><div class="data-panel-header"><strong>任务状态</strong><small>实时统计</small></div><div class="storage-lines"><div v-for="(value,key) in metrics.tasks" :key="key" class="storage-line monitor-link" role="button" @click="openAlerts(taskAlertType(String(key)))"><span>{{key}}</span><span class="mono">{{value}}</span></div></div></section><section class="data-panel"><div class="data-panel-header"><strong>队列状态</strong><small>实时积压</small></div><div class="storage-lines"><div v-for="(value,key) in health.queues" :key="key" class="storage-line" :class="{'monitor-link':queueAlertType(String(key))}" role="button" @click="queueAlertType(String(key))&&openAlerts(queueAlertType(String(key)))"><span>{{key}}</span><span class="mono">{{value}}</span></div></div></section></div></el-tab-pane>
      <el-tab-pane v-if="auth.hasAny(['USER_MANAGE'])" label="用户管理" name="users"><section class="data-panel"><el-table :data="users"><el-table-column prop="username" label="用户名"/><el-table-column prop="display_name" label="姓名"/><el-table-column prop="role" label="角色"/><el-table-column label="状态"><template #default="{row}"><el-tag :type="row.enabled?'success':'info'">{{row.enabled?'启用':'停用'}}</el-tag></template></el-table-column><el-table-column prop="updated_at" label="更新时间" min-width="170"/><el-table-column label="操作"><template #default="{row}"><el-button link :icon="Edit" @click="editUser(row)">编辑</el-button></template></el-table-column></el-table></section></el-tab-pane>
      <el-tab-pane v-if="auth.hasAny(['USER_MANAGE'])" label="权限管理" name="roles"><section class="data-panel"><el-table :data="roles"><el-table-column prop="role_code" label="角色编码"/><el-table-column prop="role_name" label="角色名称"/><el-table-column prop="description" label="说明" min-width="220"/><el-table-column label="权限" min-width="360"><template #default="{row}"><el-tag v-for="x in row.permissions" :key="x" size="small" effect="plain" style="margin:2px">{{x}}</el-tag></template></el-table-column><el-table-column label="操作"><template #default="{row}"><el-button link :icon="Edit" @click="editRole(row)">配置权限</el-button></template></el-table-column></el-table></section></el-tab-pane>
      <el-tab-pane v-if="auth.hasAny(['DICT_MANAGE'])" label="基础数据" name="basic"><div class="filter-row" style="margin-bottom:12px"><el-select v-model="selectedDictionary" style="width:220px"><el-option v-for="x in dictionaries" :key="x.id" :label="`${x.name} (${x.dict_type})`" :value="x.id"/></el-select><el-button :icon="Download" @click="exportData('CSV')">导出 CSV</el-button><el-button :icon="Download" @click="exportData('XLSX')">导出 XLSX</el-button><el-select v-model="importFormat" style="width:100px"><el-option label="CSV" value="CSV"/><el-option label="XLSX" value="XLSX"/></el-select><el-upload :show-file-list="false" :auto-upload="false" :on-change="importData"><el-button :icon="Upload">导入</el-button></el-upload></div><section class="data-panel"><el-table :data="visibleItems"><el-table-column prop="source_value" label="源值"/><el-table-column prop="target_value" label="标准值"/><el-table-column prop="description" label="说明" min-width="220"/><el-table-column label="状态"><template #default="{row}"><el-tag :type="row.enabled?'success':'info'">{{row.enabled?'启用':'停用'}}</el-tag></template></el-table-column><el-table-column label="操作" width="150"><template #default="{row}"><el-button link @click="editItem(row)">编辑</el-button><el-button link type="danger" @click="removeItem(row)">删除</el-button></template></el-table-column></el-table></section></el-tab-pane>
      <el-tab-pane v-if="auth.hasAny(['DICT_MANAGE'])" label="病理号规则设置" name="pathology-rules"><el-alert title="外部系统已有病理号时保留外部病理号；平台自主生成时按启用规则生成。本页提供规则维护和示例预览。" type="info" show-icon/><section class="data-panel" style="margin-top:12px"><el-table :data="pathologyRules"><el-table-column prop="name" label="规则名称" min-width="150"/><el-table-column prop="business_type" label="业务类型" width="140"/><el-table-column prop="prefix" label="前缀" width="90"/><el-table-column prop="year_format" label="年份格式" width="110"/><el-table-column prop="separator" label="分隔符" width="90"/><el-table-column prop="sequence_digits" label="流水号位数" width="110"/><el-table-column prop="start_sequence" label="起始流水号" width="110"/><el-table-column label="状态" width="90"><template #default="{row}"><el-tag :type="row.enabled?'success':'info'">{{row.enabled?'启用':'停用'}}</el-tag></template></el-table-column><el-table-column label="操作" width="260"><template #default="{row}"><el-button link @click="previewPathologyRule(row)">预览</el-button><el-button link :icon="Edit" @click="openPathologyRule(row)">编辑</el-button><el-button link type="danger" @click="removePathologyRule(row)">删除</el-button></template></el-table-column></el-table></section></el-tab-pane>
      <el-tab-pane v-if="auth.hasAny(['QUALITY_MANAGE'])" label="质控管理" name="quality"><div class="stats-grid" style="grid-template-columns:repeat(4,minmax(150px,1fr))"><section class="stat-card"><span>待处理异常</span><strong>{{qualityIssues.filter(x=>['PENDING','FAILED'].includes(x.status)).length}}</strong></section><section class="stat-card"><span>已修正</span><strong>{{qualityIssues.filter(x=>x.status==='CORRECTED').length}}</strong></section><section class="stat-card"><span>已忽略</span><strong>{{qualityIssues.filter(x=>x.status==='IGNORED').length}}</strong></section><section class="stat-card"><span>校验通过</span><strong>{{qualityIssues.filter(x=>x.status==='PASSED').length}}</strong></section></div><section class="data-panel"><el-table :data="qualityIssues.slice(0,100)"><el-table-column prop="business_type" label="数据对象"/><el-table-column prop="field_name" label="字段"/><el-table-column prop="error_message" label="问题说明" min-width="260"/><el-table-column prop="status" label="状态"><template #default="{row}"><el-tag :type="row.status==='PASSED'?'success':row.status==='IGNORED'?'info':'danger'">{{row.status==='PASSED'?'通过':row.status==='IGNORED'?'已忽略':'待处理'}}</el-tag></template></el-table-column></el-table></section></el-tab-pane>
      <el-tab-pane v-if="auth.hasAny(['SYSTEM_CONFIG'])" label="存储配置" name="storage"><section class="data-panel"><el-table :data="targets"><el-table-column prop="name" label="名称"/><el-table-column prop="storage_class" label="等级"/><el-table-column prop="endpoint" label="端点" min-width="230"/><el-table-column prop="bucket" label="Bucket"/><el-table-column label="状态"><template #default="{row}"><el-tag :type="row.enabled?'success':'info'">{{row.enabled?'启用':'停用'}}</el-tag></template></el-table-column><el-table-column label="操作" width="180"><template #default="{row}"><el-button link :icon="Connection" @click="testStorage(row)">测试</el-button><el-button link :icon="Edit" @click="editStorage(row)">编辑</el-button></template></el-table-column></el-table></section></el-tab-pane>
      <el-tab-pane v-if="auth.hasAny(['MONITOR_VIEW'])" label="存储监控" name="storageMetrics"><section class="data-panel"><el-table :data="metrics.storageTargets" row-class-name="monitor-link" @row-click="openStorageAlerts"><el-table-column prop="name" label="存储目标"/><el-table-column prop="storage_class" label="等级"/><el-table-column prop="status" label="状态"/><el-table-column prop="objectCount" label="对象数"/><el-table-column label="已使用"><template #default="{row}">{{formatBytes(row.usedBytes)}}</template></el-table-column><el-table-column label="可用空间"><template #default="{row}">{{formatBytes(row.availableBytes)}}</template></el-table-column><el-table-column prop="message" label="说明" min-width="220"/></el-table></section></el-tab-pane>
      <el-tab-pane v-if="auth.hasAny(['MONITOR_VIEW'])" label="告警" name="alerts"><section class="data-panel"><el-table :data="visibleAlertEvents"><el-table-column prop="severity" label="级别" width="100"><template #default="{row}"><el-tag :type="row.severity==='CRITICAL'?'danger':'warning'">{{row.severity}}</el-tag></template></el-table-column><el-table-column prop="event_type" label="类型" min-width="180"/><el-table-column prop="message" label="内容" min-width="300"/><el-table-column prop="status" label="状态" width="130"/><el-table-column prop="first_seen_at" label="首次出现" min-width="170"/><el-table-column prop="occurrence_count" label="次数" width="80"/><el-table-column label="操作" width="170"><template #default="{row}"><el-button link :icon="Check" :disabled="row.status!=='OPEN'" @click="alertAction(row,'acknowledge')">确认</el-button><el-button link type="danger" :icon="Close" :disabled="row.status==='CLOSED'" @click="alertAction(row,'close')">关闭</el-button></template></el-table-column></el-table></section></el-tab-pane>
      <el-tab-pane v-if="auth.hasAny(['SYSTEM_CONFIG'])" label="系统参数" name="config"><section class="data-panel"><el-table :data="configs"><el-table-column prop="config_key" label="配置项"/><el-table-column prop="config_value" label="配置值"/><el-table-column prop="description" label="说明" min-width="240"/><el-table-column label="操作"><template #default="{row}"><el-button link @click="editConfig(row)">编辑</el-button></template></el-table-column></el-table></section></el-tab-pane>
      <el-tab-pane v-if="auth.hasAny(['LOG_VIEW'])" label="日志管理" name="logs"><section class="data-panel"><el-table :data="logs"><el-table-column prop="username" label="用户"/><el-table-column prop="operation" label="操作"/><el-table-column prop="module" label="模块"/><el-table-column prop="business_id" label="业务ID"/><el-table-column prop="created_at" label="时间" min-width="170"/><el-table-column prop="result" label="结果"/><el-table-column prop="detail" label="详情" min-width="240"/></el-table></section></el-tab-pane>
    </el-tabs>
    <el-dialog v-model="userDialog" :title="editingId?'编辑用户':'新增用户'" width="min(480px,92vw)"><el-form :model="userForm" label-width="80px"><el-form-item label="用户名"><el-input v-model="userForm.username" :disabled="!!editingId"/></el-form-item><el-form-item label="姓名"><el-input v-model="userForm.displayName"/></el-form-item><el-form-item label="密码"><el-input v-model="userForm.password" type="password" show-password/></el-form-item><el-form-item label="角色"><el-select v-model="userForm.role" style="width:100%"><el-option v-for="x in roles" :key="x.role_code" :label="x.role_name" :value="x.role_code"/></el-select></el-form-item><el-form-item label="启用"><el-switch v-model="userForm.enabled"/></el-form-item></el-form><template #footer><el-button @click="userDialog=false">取消</el-button><el-button type="primary" @click="saveUser">保存</el-button></template></el-dialog>
    <el-dialog v-model="roleDialog" :title="`角色授权 · ${roleForm.name}`" width="min(720px,94vw)"><el-checkbox-group v-model="roleForm.permissions" class="permission-grid"><el-checkbox v-for="x in permissions" :key="x.permission_code" :value="x.permission_code">{{x.permission_name}} <small>{{x.permission_code}}</small></el-checkbox></el-checkbox-group><template #footer><el-button @click="roleDialog=false">取消</el-button><el-button type="primary" @click="saveRole">保存授权</el-button></template></el-dialog>
    <el-dialog v-model="itemDialog" title="基础数据项" width="min(480px,92vw)"><el-form :model="itemForm" label-width="80px"><el-form-item label="源值"><el-input v-model="itemForm.sourceValue"/></el-form-item><el-form-item label="标准值"><el-input v-model="itemForm.targetValue"/></el-form-item><el-form-item label="说明"><el-input v-model="itemForm.description"/></el-form-item><el-form-item label="启用"><el-switch v-model="itemForm.enabled"/></el-form-item></el-form><template #footer><el-button @click="itemDialog=false">取消</el-button><el-button type="primary" @click="saveItem">保存</el-button></template></el-dialog>
    <el-dialog v-model="storageDialog" title="存储目标" width="min(560px,92vw)"><el-form :model="storageForm" label-width="100px"><el-form-item label="名称"><el-input v-model="storageForm.name"/></el-form-item><el-form-item label="等级"><el-segmented v-model="storageForm.storageClass" :options="['HOT','ARCHIVE','BACKUP','TEST']"/></el-form-item><el-form-item label="Endpoint"><el-input v-model="storageForm.endpoint"/></el-form-item><el-form-item label="Bucket"><el-input v-model="storageForm.bucket"/></el-form-item><el-form-item label="Access Key"><el-input v-model="storageForm.accessKey"/></el-form-item><el-form-item label="Secret Key"><el-input v-model="storageForm.secretKey" type="password" show-password/></el-form-item><el-form-item label="启用"><el-switch v-model="storageForm.enabled"/></el-form-item></el-form><template #footer><el-button @click="storageDialog=false">取消</el-button><el-button type="primary" @click="saveStorage">保存</el-button></template></el-dialog>
    <el-dialog v-model="configDialog" title="编辑系统参数" width="min(480px,92vw)"><el-form :model="configForm" label-width="80px"><el-form-item label="配置项"><el-input v-model="configForm.configKey" disabled/></el-form-item><el-form-item label="配置值"><el-input v-model="configForm.configValue"/></el-form-item><el-form-item label="说明"><el-input v-model="configForm.description" type="textarea"/></el-form-item></el-form><template #footer><el-button @click="configDialog=false">取消</el-button><el-button type="primary" @click="saveConfig">保存</el-button></template></el-dialog>
    <el-dialog v-model="pathologyRuleDialog" :title="editingPathologyRuleId?'编辑病理号规则':'新增病理号规则'" width="min(560px,92vw)"><el-form :model="pathologyRuleForm" label-width="100px"><el-form-item label="规则名称"><el-input v-model="pathologyRuleForm.name"/></el-form-item><el-form-item label="业务类型"><el-input v-model="pathologyRuleForm.businessType"/></el-form-item><el-row :gutter="14"><el-col :span="12"><el-form-item label="前缀"><el-input v-model="pathologyRuleForm.prefix" placeholder="如 P"/></el-form-item></el-col><el-col :span="12"><el-form-item label="年份格式"><el-input v-model="pathologyRuleForm.yearFormat" placeholder="yyyy"/></el-form-item></el-col></el-row><el-row :gutter="14"><el-col :span="12"><el-form-item label="分隔符"><el-input v-model="pathologyRuleForm.separator"/></el-form-item></el-col><el-col :span="12"><el-form-item label="流水号位数"><el-input-number v-model="pathologyRuleForm.sequenceDigits" :min="1" :max="12"/></el-form-item></el-col></el-row><el-form-item label="起始流水号"><el-input-number v-model="pathologyRuleForm.startSequence" :min="0"/></el-form-item><el-form-item label="启用"><el-switch v-model="pathologyRuleForm.enabled"/></el-form-item></el-form><template #footer><el-button @click="pathologyRuleDialog=false">取消</el-button><el-button type="primary" @click="savePathologyRule">保存规则</el-button></template></el-dialog>
  </div>
</template>
