package com.medreport.report;
import com.medreport.auth.RequirePermission;import com.medreport.common.ApiResponse;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.web.bind.annotation.*;import java.util.*;
@RestController @RequestMapping("/api/report-endpoints") @RequirePermission("REPORT_ENDPOINT_MANAGE")
public class ReportEndpointController{
 private final JdbcTemplate jdbc; public ReportEndpointController(JdbcTemplate jdbc){this.jdbc=jdbc;}
 @GetMapping public ApiResponse<List<Map<String,Object>>> list(){List<Map<String,Object>> rows=jdbc.queryForList("SELECT id,name,endpoint_url,transport_mode,auth_type,username,client_cert_path,trust_store_path,tls_verify,enabled,created_at,updated_at FROM report_endpoint ORDER BY id DESC");return ApiResponse.ok(rows);}
 @PostMapping public ApiResponse<Map<String,Object>> create(@RequestBody Map<String,Object>b){jdbc.update("INSERT INTO report_endpoint(name,endpoint_url,transport_mode,auth_type,username,password_encrypted,token_encrypted,client_cert_path,client_key_path,trust_store_path,tls_verify,enabled) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)",b.get("name"),b.get("endpointUrl"),b.getOrDefault("transportMode","HTTP"),b.getOrDefault("authType","NONE"),b.get("username"),b.get("password"),b.get("token"),b.get("clientCertPath"),b.get("clientKeyPath"),b.get("trustStorePath"),bool(b.getOrDefault("tlsVerify",true))?1:0,bool(b.getOrDefault("enabled",true))?1:0);long id=jdbc.queryForObject("SELECT LAST_INSERT_ID()",Long.class);return ApiResponse.ok(Map.of("id",id));}
 @PutMapping("/{id}") public ApiResponse<Void> update(@PathVariable long id,@RequestBody Map<String,Object>b){jdbc.update("UPDATE report_endpoint SET name=COALESCE(?,name),endpoint_url=COALESCE(?,endpoint_url),transport_mode=COALESCE(?,transport_mode),auth_type=COALESCE(?,auth_type),tls_verify=COALESCE(?,tls_verify),enabled=COALESCE(?,enabled) WHERE id=?",b.get("name"),b.get("endpointUrl"),b.get("transportMode"),b.get("authType"),b.containsKey("tlsVerify")?(bool(b.get("tlsVerify"))?1:0):null,b.containsKey("enabled")?(bool(b.get("enabled"))?1:0):null,id);return ApiResponse.ok();}
 @PostMapping("/{id}/test") public ApiResponse<Map<String,Object>> test(@PathVariable long id){Map<String,Object>e=jdbc.queryForMap("SELECT endpoint_url,tls_verify,enabled FROM report_endpoint WHERE id=?",id);return ApiResponse.ok(Map.of("configured",true,"tlsVerify",e.get("tls_verify"),"enabled",e.get("enabled")));}
 private boolean bool(Object v){return v instanceof Boolean b?b:v instanceof Number n?n.intValue()!=0:Boolean.parseBoolean(String.valueOf(v));}
}
