package com.medreport.report;

import com.medreport.auth.RequirePermission;
import com.medreport.common.ApiResponse;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.server.ResponseStatusException;

import java.io.*;
import java.nio.file.*;
import java.security.MessageDigest;
import java.util.*;

/** Mock resumable receiver and persisted transfer session used for integration tests. */
@RestController
@RequestMapping("/api/mock-resumable")
public class ResumableTransferController {
    private final JdbcTemplate jdbc; private final Path root;
    public ResumableTransferController(JdbcTemplate jdbc,@Value("${app.report-dir:./data/reports}") String dir){this.jdbc=jdbc;this.root=Path.of(dir,".resumable");}
    @PostMapping("/init") @RequirePermission("REPORT_SEND") public ApiResponse<Map<String,Object>> init(@RequestBody Map<String,Object>b){try{long total=((Number)b.getOrDefault("totalBytes",0)).longValue();int chunk=((Number)b.getOrDefault("chunkSize",8*1024*1024)).intValue();if(chunk<1024*1024||chunk>64*1024*1024)throw new IllegalArgumentException("chunkSize must be 1MB..64MB");String id=UUID.randomUUID().toString();Files.createDirectories(root.resolve(id));int n=(int)((total+chunk-1)/chunk);jdbc.update("INSERT INTO report_transfer_session(sender_type,endpoint,file_path,total_bytes,chunk_size,total_chunks,status,started_at,last_activity_at) VALUES ('MOCK',?, ?,?,?,?,'UPLOADING',NOW(),NOW())", "mock:"+id,root.resolve(id).toString(),total,chunk,n);long sid=jdbc.queryForObject("SELECT LAST_INSERT_ID()",Long.class);for(int i=0;i<n;i++){long off=(long)i*chunk;int size=(int)Math.min(chunk,total-off);jdbc.update("INSERT INTO report_transfer_chunk(session_id,chunk_index,offset_bytes,chunk_size) VALUES (?,?,?,?)",sid,i,off,size);}return ApiResponse.ok(Map.of("sessionId",sid,"uploadId",id,"chunkSize",chunk,"totalChunks",n));}catch(IOException e){throw new ResponseStatusException(HttpStatus.INTERNAL_SERVER_ERROR,e.getMessage());}}
    @PutMapping("/{uploadId}/chunks/{index}") @RequirePermission("REPORT_SEND") public ApiResponse<Map<String,Object>> chunk(@PathVariable String uploadId,@PathVariable int index,@RequestHeader("X-Chunk-SHA256") String expected,@RequestBody byte[] body){Map<String,Object>s=session(uploadId);long sid=((Number)s.get("id")).longValue();Map<String,Object> c=chunk(sid,index);String actual=sha(body);if(!actual.equalsIgnoreCase(expected))throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"chunk SHA-256 mismatch");String status=String.valueOf(c.get("status"));if("SUCCESS".equals(status)){if(!actual.equalsIgnoreCase(String.valueOf(c.get("sha256"))))throw new ResponseStatusException(HttpStatus.CONFLICT,"chunk hash conflict");return ApiResponse.ok(Map.of("status","already_uploaded"));}try{Path p=Path.of(String.valueOf(s.get("file_path")),String.valueOf(index));Files.write(p,body,StandardOpenOption.CREATE,StandardOpenOption.TRUNCATE_EXISTING);jdbc.update("UPDATE report_transfer_chunk SET sha256=?,status='SUCCESS',uploaded_at=NOW(),attempt_count=attempt_count+1 WHERE session_id=? AND chunk_index=?",actual,sid,index);jdbc.update("UPDATE report_transfer_session SET uploaded_bytes=uploaded_bytes+?,completed_chunks=completed_chunks+1,last_activity_at=NOW() WHERE id=?",body.length,sid);return ApiResponse.ok(Map.of("status","uploaded","sha256",actual));}catch(IOException e){throw new ResponseStatusException(HttpStatus.INTERNAL_SERVER_ERROR,e.getMessage());}}
    @GetMapping("/{uploadId}/status") @RequirePermission("REPORT_SEND") public ApiResponse<Map<String,Object>> status(@PathVariable String uploadId){Map<String,Object>s=session(uploadId);long sid=((Number)s.get("id")).longValue();List<Integer> done=jdbc.queryForList("SELECT chunk_index FROM report_transfer_chunk WHERE session_id=? AND status='SUCCESS' ORDER BY chunk_index",Integer.class,sid);return ApiResponse.ok(Map.of("uploadedChunks",done,"uploadedBytes",s.get("uploaded_bytes"),"status",s.get("status")));}
    @PostMapping("/{uploadId}/complete") @RequirePermission("REPORT_SEND") public ApiResponse<Map<String,Object>> complete(@PathVariable String uploadId){Map<String,Object>s=session(uploadId);long sid=((Number)s.get("id")).longValue();int pending=jdbc.queryForObject("SELECT COUNT(*) FROM report_transfer_chunk WHERE session_id=? AND status<>'SUCCESS'",Integer.class,sid);if(pending>0)throw new ResponseStatusException(HttpStatus.CONFLICT,"chunks missing");try{Path dir=Path.of(String.valueOf(s.get("file_path")));Path out=dir.resolve("payload.bin");try(OutputStream os=Files.newOutputStream(out)){for(int i=0;i<((Number)s.get("total_chunks")).intValue();i++)Files.copy(dir.resolve(String.valueOf(i)),os);}String hash=sha(out);jdbc.update("UPDATE report_transfer_session SET status='SUCCESS',whole_sha256=?,completed_at=NOW(),last_activity_at=NOW() WHERE id=?",hash,sid);return ApiResponse.ok(Map.of("status","SUCCESS","remoteSha256",hash));}catch(IOException e){throw new ResponseStatusException(HttpStatus.INTERNAL_SERVER_ERROR,e.getMessage());}}
    @GetMapping("/sessions") @RequirePermission("REPORT_SEND") public ApiResponse<List<Map<String,Object>>> sessions(){return ApiResponse.ok(jdbc.queryForList("SELECT id,job_id,batch_id,total_bytes,uploaded_bytes,chunk_size,total_chunks,completed_chunks,status,whole_sha256,last_error,last_activity_at FROM report_transfer_session ORDER BY id DESC LIMIT 300"));}
    @PostMapping("/sessions/{id}/pause") @RequirePermission("REPORT_TRANSFER_MANAGE") public ApiResponse<Void> pause(@PathVariable long id){jdbc.update("UPDATE report_transfer_session SET status='PAUSED' WHERE id=? AND status IN ('UPLOADING','INTERRUPTED')",id);return ApiResponse.ok();}
    @PostMapping("/sessions/{id}/resume") @RequirePermission("REPORT_TRANSFER_MANAGE") public ApiResponse<Void> resume(@PathVariable long id){jdbc.update("UPDATE report_transfer_session SET status='UPLOADING',last_activity_at=NOW() WHERE id=? AND status IN ('PAUSED','INTERRUPTED','FAILED')",id);return ApiResponse.ok();}
    @PostMapping("/sessions/{id}/retry") @RequirePermission("REPORT_TRANSFER_MANAGE") public ApiResponse<Void> retry(@PathVariable long id){jdbc.update("UPDATE report_transfer_session SET status='UPLOADING',retry_count=retry_count+1,last_error=NULL WHERE id=?",id);return ApiResponse.ok();}
    private Map<String,Object> session(String uploadId){List<Map<String,Object>> r=jdbc.queryForList("SELECT * FROM report_transfer_session WHERE endpoint=?", "mock:"+uploadId); if(r.isEmpty()) r=jdbc.queryForList("SELECT * FROM report_transfer_session WHERE file_path LIKE ?", "%"+uploadId+"%"); if(r.isEmpty())throw new ResponseStatusException(HttpStatus.NOT_FOUND,"upload not found");return r.getFirst();}
    private Map<String,Object> chunk(long sid,int i){List<Map<String,Object>>r=jdbc.queryForList("SELECT * FROM report_transfer_chunk WHERE session_id=? AND chunk_index=?",sid,i);if(r.isEmpty())throw new ResponseStatusException(HttpStatus.NOT_FOUND,"chunk not found");return r.getFirst();}
    private String sha(byte[] b){try{return hex(MessageDigest.getInstance("SHA-256").digest(b));}catch(Exception e){throw new IllegalStateException(e);}}
    private String sha(Path p)throws IOException{try{MessageDigest d=MessageDigest.getInstance("SHA-256");try(InputStream in=Files.newInputStream(p)){byte[]b=new byte[1024*1024];for(int n;(n=in.read(b))>0;)d.update(b,0,n);}return hex(d.digest());}catch(Exception e){throw new IOException(e);}}
    private String hex(byte[] b){StringBuilder s=new StringBuilder();for(byte x:b)s.append(String.format("%02x",x));return s.toString();}
}
